### ISSUE TITLE
full combo filter flash

### ISSUE THREAD

**Issue by sangyeolbaek** [dguzek/Simply-Love-SM5#109]
Not that it is a big deal, but:

At the end of a song, if you have filter enabled, and full combo it, you see a colorful flash before transitioning from gameplay to the results screen.
But I notice it doesn't do so for "full GREAT combos" in ECFA or "full GOOD combos" in StomperZ. 
Is this intentional?

**Comment by andrewipark** [comment]
The logic for flashing screen filter is:
- if not "is full combo" don't do anything
- figure out which FC type it is and flash that color

Unfortunately, the "is full combo" check is hardcoded to W3 (the third judgement) by SM, so for ECFA and stomperz where a W4 full combo is possible, the check for W4 full combo is never reached.

**Comment by dguzek** [comment]
This has been resolved for the v4.8 release by d869098044121a8197bc49cd440d98edd042f23c.
