### ISSUE TITLE
Font a bit too large in the menu when you press "B" on editor mode

### ISSUE THREAD

**Issue by sangyeolbaek** [dguzek/Simply-Love-SM5#120]
![screen shot 2018-06-15 at 12 14 17 am](https://user-images.githubusercontent.com/36245205/41823312-94c303b6-77c3-11e8-87dd-9156c8e048f8.png)

**Comment by dguzek** [comment]
Resolved by 4d6fc1914dc6ebbe8e54c6b8768c28adc3597022.
