### ISSUE TITLE
No UI elements show up

### ISSUE THREAD

**Issue by 4techguns** [dguzek/Simply-Love-SM5#131]
When I start StepMania 5.1 with the theme installed, no UI elements show up.
There is a video for proof:
https://mega.nz/#!ebxWkSJD

**Comment by dguzek** [comment]
I would need to key to decrypt that mega link.

1. What version of SM5.1 are you using?
2. What version of Simply Love are you using?
3. Where do you have Simply Love installed to?

**Comment by 4techguns** [comment]
I have StepMania 5.1 installed in the Games folder where it is supposed to be, also with a backup StepMania 5 folder in the Games folder.
I don't know what version of the skin I downloaded. The theme is installed in the Themes folder where it is supposed to be.
Also, I got the link with the key: https://mega.nz/#!ebxWkSJD!zAjBNPTu58-W-a8uSBGko5ewSWVgs96gbGt7LbbmU3I

**Comment by 4techguns** [comment]
I think (re)downloading the latest version will fix the problem.

**Comment by dguzek** [comment]
> I think (re)downloading the latest version will fix the problem.

Is this issue resolved, then?

**Comment by dguzek** [comment]
Any news on this, @4techguns?

**Comment by dguzek** [comment]
I'll close this issue now under the assumption that is has been resolved.

If you are still having issues installing the theme, @4techguns, feel free to re-open it and I'll try to help you out.
