### ISSUE TITLE
freeze after select profile

### ISSUE THREAD

**Issue by gebgebgeb** [dguzek/Simply-Love-SM5#137]
if you're in coinmode pay, have select profile on, and both players press enter at approximately the same time off the title screen, the game freezes after the select profile screen

**Comment by dguzek** [comment]
I am unable to recreate this bug, so you'll need to provide more information.

What version of Simply Love are you using?
What is your `Premium` setting set to?
Do you have ScreenSelectColor Disabled, or do you have RainbowMode enabled?
Why do you have ScreenSelectProfile enabled in CoinMode Pay?

Regarding the last question in particular, that combination really doesn't make sense for public arcade machines.  Any chaotic or less-than-trustworthy person could choose any other profile.  It makes more sense to use USB-based profiles.

**Comment by gebgebgeb** [comment]
SL version is 4.8.1. Good point about the last question; I actually stumbled across this accidentally when looking to reproduce a bug that I had seen in an older version of SL, where pressing both enter keys quickly would eat up 2 credits but not allow you to select 2 players on the 1player/2player/doubles select screen. Although, in this version of SL, I can't find the option that toggles whether that screen appears.

I just checked on my setup, and I was able to reproduce the freeze on all premium settings, and whether or not ScreenSelectColor was enabled. Maybe more relevantly, I also got the freeze with ScreenSelectProfile off and ScreenSelectColor on, which seems like an actually realistic setup for a public machine.

**Comment by dguzek** [comment]
I should have been more clear in asking my own questions.  I apologize about that.

Are you using the release version 4.8.1 or HEAD from GitHub?  Commit 407cb459f0139449ccdd682cf95ae9e09d3d9394 doesn't appear in 4.8.1, and I'm wondering if that fixed the issue you're describing, as I'm unable to recreate it.

---

If you *are* already using an up-to-date copy of SL from GitHub, then I'll need to be more specific by what you mean by "got the freeze."  

• Is StepMania completely locked up?

• Can you still hold <kbd>F3</kbd> to get into the debug menu?  If so, that indicates that StepMania hasn't completely locked up.

• If you can get into the debug menu by holding <kbd>F3</kbd>, then try holding <kbd>F3</kbd> and then tapping  <kbd>F6</kbd> to get into the Themer Menu.  What screen does it indicate you are currently on when the "freeze" occurs?

For example, the Themer Menu here indicates that I'm on ScreenSelectColor:
<img width="1207" alt="screen shot 2018-11-09 at 12 43 37 pm" src="https://user-images.githubusercontent.com/1253483/48278979-2d4cea00-e41d-11e8-9ec1-4a9bb8f69a98.png">

**Comment by dguzek** [comment]
> Although, in this version of SL, I can't find the option that toggles whether that screen appears.

You are probably thinking of this:
<img width="1620" alt="screen shot 2018-11-09 at 12 46 24 pm" src="https://user-images.githubusercontent.com/1253483/48279092-8452bf00-e41d-11e8-80c2-fb94bdd91775.png">

**Comment by gebgebgeb** [comment]
I was on commit `6db7360` (the one linked on the releases page), but I just tried it again on HEAD and I'm still able to get the behavior. I've attached a video of what happens: the program doesn't hang, it just doesn't display any UI elements, and the themer menu seems to indicate that it's still on the select color screen.

Thanks for pointing out the 1/2/double player setting; I also checked for that one, and it seems to be fixed on head.

[2018-11-09 12-56-34.flv.zip](https://github.com/dguzek/Simply-Love-SM5/files/2566979/2018-11-09.12-56-34.flv.zip)

**Comment by dguzek** [comment]
Interesting.  It looks like a themeside Lua error is occurring in ScreenSelectColor somewhere.

If you can, press <kbd>8</kbd> while in the Themer Menu to toggle `ShowThemeErrors` on, then recreate the bug, and you should hopefully get an error message displayed briefly at the top of the screen in a blue/green box when the error occurs.  Assuming that happens, screenshot the error and attach it here.

**Comment by gebgebgeb** [comment]
![2018-11-09-131044_3640x1920_scrot](https://user-images.githubusercontent.com/30820165/48280231-07c1df80-e421-11e8-9aa5-c7c2c832c137.png)

**Comment by dguzek** [comment]
It looks like this error is occurring because your theme is configured in Simply Love Options to have a Preferred Style of *1 Player*, but you're joining both players on ScreenTitleJoin.  While this combination of settings and actions doesn't really make sense, I agree that the theme should be error free, and that it shouldn't be possible to back oneself into such a corner at all.

I'll think about how I want to handle this and reply here once something is done.

**Comment by gebgebgeb** [comment]
ah, ok that makes sense. Thank!

**Comment by dguzek** [comment]
Let me know if 7e53185023cff9f8f8fdb9409568db2ff3a94cc2 fixes the issue for you.

**Comment by gebgebgeb** [comment]
it's fixed, thanks for the quick response!
