### ISSUE TITLE
ecfa mode doesn't remember last song played on reboot

### ISSUE THREAD

**Issue by gebgebgeb** [dguzek/Simply-Love-SM5#138]
not sure if there's a specific setting that triggers this behavior, but in competitive mode, if I clear a song, close the game, and open it again, it starts the scroll wheel at the last song I cleared (this is the desired behavior). ECFA mode works like this if I just use esc to go back to the title screen, but if I close the game and open it again, the scroll wheel starts at the last song cleared in competitive mode.

**Comment by dguzek** [comment]
I haven't looked too much into this, but I anticipate that it will not be fixed any time soon.

The engine stores information like this in (somewhere) in Stats.xml and Simply Love uses a unique Stats.xml file per gamemode, resulting in:

  * Stats.xml
  * Casual-Stats.xml
  * ECFA-Stats.xml
  * StomperZ-Stats.xml

Simply Love assumes that "Competitive" is the default state when loading the theme and loads Stats.xml when initializing the theme.  It then uses functionality added in https://github.com/stepmania/stepmania/pull/1040 to reload different stats files as needed.  (This is why if a particular stats file is *very* large, the engine seems to briefly hang when switching game modes – it is re-parsing potentially hundreds of megabytes of xml.)

If the engine's sense of CurrentSong isn't set properly when reloading a new stats file, it's probably a minor oversight in https://github.com/stepmania/stepmania/pull/1040.  I don't know enough C++ to attempt to fix the engine, myself, so it's probably not going to be fixed.

**Comment by gebgebgeb** [comment]
thanks for looking into it!
