### ISSUE TITLE
Screen filter broken

### ISSUE THREAD

**Issue by camsta4** [dguzek/Simply-Love-SM5#14]
The Screen Filter option is no longer working on any setting (Dark, Darker, Darkest).
Running Stepmania 5.0.6.

**Comment by dguzek** [comment]
Hmm, ScreenFilters work fine for me (and everyone else I know using this theme).  If you can provide more information, I can attempt to help you.

1. What operating system are you using?
2. Do you have this theme installed in your StepMania user data directory or in the StepMania application directory?
3. Did you recently upgrade from an older version of StepMania when ScreenFilters stopped working?
4. Did you change anything else when ScreenFilters stopped working?

**Comment by camsta4** [comment]
1. Windows 8.1
2. In the StepMania application directory
3. May have gone 5.0.5 --> 5.0.6
4. Nothing else changed.

They were previously working for me too, up until about around the March 3rd or march 5th commits
I downloaded a new version of the theme around that time and they haven't worked since.

I'm at work at the moment, when I get home I'll try on my other PC and also try reverting to SM 5.0.5.

**Comment by camsta4** [comment]
Replaced the theme on my other PC (Windows XP, SM 5.0.5) and the filters no longer work there either. Were working on this PC until I copied the latest theme download over tonight., changed nothing else.

**Comment by dguzek** [comment]
Please let me know if [this commit](https://github.com/dguzek/Simply-Love-SM5/commit/19b1f6146eb6807ca711e7f967c1789e130e64c6) resolves this issue for you.

It's mildly disconcerting to me that that I only discovered this problem by using Windows (no errors were logged on OS X or Linux).

**Comment by camsta4** [comment]
Yes that change did the trick, the filters are working again for all values (dark,darker,darkest).
Thanks, issue's resolved.
