### ISSUE TITLE
Question: Are the graphics templates for the input screen available?

### ISSUE THREAD

**Issue by kategray** [dguzek/Simply-Love-SM5#143]
I'd like to add a lights output test screen, and was wondering if there were any .psd/etc. available for the assets used in the input test screen.

**Comment by StefanoFiumara** [comment]
The .png assets are available in /BGAnimations/ScreenTestInput underlay/visuals folder, do you need more than this?

**Comment by kategray** [comment]
I was just wondering if they were created in Photoshop, or something that would make it easier for me to make more.

**Comment by kategray** [comment]
That would be handy.

**Comment by dguzek** [comment]
This is all I have.  Hopefully it helps!
https://drive.google.com/file/d/1lvJf1RD8Vd9dvs9uGMo2w97Dx9XH0LXe/view?usp=sharing
