### ISSUE TITLE
When in "Only Dedicated Button" mode MenuUp + MenuDown doesn't close group

### ISSUE THREAD

**Issue by FuriousDCSL** [dguzek/Simply-Love-SM5#145]
When in "Only Dedicated Button" mode MenuUp + MenuDown doesn't close group.

For example i got into Pack #1 and scroll down a bit, to exit the pack i would expect under only dedicate buttons MenuUp + MenuDown would escape, but i have to use Up+Down on the pad.

**Comment by dguzek** [comment]
This is true, but not a bug.  The intent was to use Up+Down on a 4-panel pad.

MenuUp + MenuDown working when `OnlyDedicatedMenuButtons=1` is an oversight.

**Comment by FuriousDCSL** [comment]
how is this only dedicated buttons then?

**Comment by FuriousDCSL** [comment]
If i have to use pad buttons, and can't use the menu buttons how is this considered Dedicated buttons only?  

When i am selecting music i don't want to use the pad buttons at all.

I figured out how to change it for my own use. 

Change line 1391 of metrics.ini to:
CloseCurrentFolder=PREFSMAN:GetPreference("OnlyDedicatedMenuButtons") and "MenuUp-MenuDown" or "Up-Down"

**Comment by dguzek** [comment]
> If i have to use pad buttons, and can't use the menu buttons

conflicts with

> When i am selecting music i don't want to use the pad buttons at all.

I don't understand what you're asking or requesting.

**Comment by dguzek** [comment]
Woah, you're running SM5 on a DDR Ace cabinet?  I didn't realize anyone was doing that.  Interesting.

Still, the intended behavior was definitely, 100% to have pad players perform an Up+Down jump on their 4-panel dance pad to close the pack.

**Comment by FuriousDCSL** [comment]
not on ace cab, home brew cab where i made control panel similar to ace

**Comment by FuriousDCSL** [comment]
I though that was what ThreeKeyNavigation was for.

**Comment by Horsey-** [comment]
Can confirm, I have the ace-style buttons as well (JPAC+LumenAR for IO)

**Comment by dguzek** [comment]
> Can confirm

What are you confirming?

**Comment by Horsey-** [comment]
that there are people using the 5 button navigation scheme from DDR Ace (I actually have 6 buttons because I wanted a red cancel button, but I highly doubt anyone else has that setup bedsides myself)

**Comment by dguzek** [comment]
Ah, okay.  Thank you for clarifying.

To repeat myself:
> the intended behavior was definitely, 100% to have pad players perform an Up+Down jump on their 4-panel dance pad to close the pack.

The code is working as intended as far as I can see.
