### ISSUE TITLE
Font size in SM 5.0.7RC

### ISSUE THREAD

**Issue by Fenrirthviti** [dguzek/Simply-Love-SM5#16]
Several UI elements (combo count, percentage count in game, title menu, etc) have incorrect font sizes since upgrading to SM 5.0.7RC

See a few screenshots: http://imgur.com/a/1SkDZ

**Comment by dguzek** [comment]
This bug was introduced engine-side into 5.0.7rc and has already been fixed.  You can use a nightly build of StepMania 5, rollback to 5.0.6, or wait until 5.0.7 final.

See: http://www.stepmania.com/forums/themes/show/2209#post5346

**Comment by Fenrirthviti** [comment]
5.0.7 final seems to have not corrected this issue. Should I submit a new bug report for SM5 direct?
