### ISSUE TITLE
Local profiles erroneously save with arrows, bg, etc turned off.

### ISSUE THREAD

**Issue by OmnipotentEntity** [dguzek/Simply-Love-SM5#18]
This seems to be due to the creation of an empty file for each of the hide XYZ options.  Tested on HEAD of Simply-Love-SM5 and 5.0.7rc of stepmania.

To reproduce, create a local profile.  Play a song.  Exit the game.  Load the game.  Play a song.  Observe that bg, health, percent, etc are hidden.

**Comment by dguzek** [comment]
I think this has already been addressed via issue #15 but let me know if it hasn't.

**Comment by OmnipotentEntity** [comment]
Oh lordy. I should pull again.  It's been 3 days.  I probably came in right under it. Boo.
