### ISSUE TITLE
Sounds are encoded at random sample rates

### ISSUE THREAD

**Issue by kyzentun** [dguzek/Simply-Love-SM5#20]
I finally figured out why I was getting seg faults in the audio code with Simply Love:
Most of the sounds are encoded at various strange bit rates instead of 44.1 kHz.

You can fix this on the command line (if you have vorbis-tools installed on debian, hopefully OS X has an equivalent)
```
oggdec *.ogg
oggenc -q 5 --resample 44100 *.wav
```
Or this tarball: http://kyzentun.tejat.net/random_junk/sl_fixed_sounds.tbz2

**Comment by dguzek** [comment]
This should be resolved as of commit 5870444787c21c6a718f1702c1619f3e6f146e7d.  Thank you for finding this issue; I'm not sure I would have ever.

Also, thank you for recommending vorbis-tools.  It made light work of the issue. :)
