### ISSUE TITLE
No banner transition when moving off fallback banner

### ISSUE THREAD

**Issue by camsta4** [dguzek/Simply-Love-SM5#21]
Not a big deal, but something I noticed none the less.
When browsing the song wheel, normally the banners cross-fade in and out of each other.

When a fallback banner is present the cross-fade occurs when moving on to the fallback banner from a real banner. But when moving off the fallback banner onto a real banner the transition is missing and the real banner just snaps instantly into view.

**Comment by dguzek** [comment]
This is an unfortunate side-effect of using the SM engine's FadingBanner class on ScreenSelectMusic.  I would have *all* banners appear without transition if feasible.

You can read my fairly detailed explanations in the three commits in which I tried to fix this:

1: https://github.com/dguzek/Simply-Love-SM5/commit/368b16fbd8eccbc7e146825a7fa3ad0c97cc6b1c
2: https://github.com/dguzek/Simply-Love-SM5/commit/f35857a42c873f17fd74a5044254d019aaa74dd5
3: https://github.com/dguzek/Simply-Love-SM5/commit/624998c0c7901513fedbcac3d4e0ee2068e782f1

**Comment by camsta4** [comment]
I see, looks like you had fun with that one :P
Thanks for the explanation.
