### ISSUE TITLE
Marathon mode doesn't show measure counter lookahead after the first song

### ISSUE THREAD

**Issue by hollowaytape** [dguzek/Simply-Love-SM5#217]
Playing some ECS X.5 courses in marathon mode in v4.9.1, I noticed that measure counter lookahead is only available in the first song of each course. After the first song, only the current measure counter is displayed.

I reproduced this in 4.9.0 as well.

[Here's a video where this is visible.](https://www.youtube.com/watch?v=wiio-MeR2vI) Lookahead visible at 0:30, then disappears at 4:08.

**Comment by natano** [comment]
This is fixed in https://github.com/Simply-Love/Simply-Love-SM5/commit/2422fe77e8c23231334a2dedf0efd0e83cfd14c3.
Thanks for reporting the issue and uploading the video, @hollowaytape!
