### ISSUE TITLE
SM() util function no longer writes to log

### ISSUE THREAD

**Issue by jordando** [dguzek/Simply-Love-SM5#219]
not sure if this is intended but MESSAGEMAN:Broadcast("SystemMessage", {}) doesn't seem to seem to write to the log but the old SCREENMAN:SystemMessage() does which is useful for looking at larger tables. i know you can just use trace() or something but it was more convenient using SM.

**Comment by natano** [comment]
This was fixed in https://github.com/Simply-Love/Simply-Love-SM5/commit/266b6c9e5348f4625b4dbbb37ee00ebefc703068. Thanks for the report, @jordando!
