### ISSUE TITLE
Fallback banner errors

### ISSUE THREAD

**Issue by camsta4** [dguzek/Simply-Love-SM5#22]
On the song wheel the banner displays the 3 heart fallback, but after song ends during transition to results screen there is a theme error, looks like it's trying to find the fallback banner in the current songs folder, which doesn't exist. Then a big pink banner is shown in place.

Also get the same error at the Summary screen after game over.

![capture](https://cloud.githubusercontent.com/assets/11501181/7045417/92bbfe22-de30-11e4-8282-16ea6d33ab67.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11501181/7045420/958ba454-de30-11e4-93d4-bb62b8749da7.PNG)

**Comment by dguzek** [comment]
In this theme, the fallback banner is *always* present.  It is always loaded when the screen that requires it initializes, and, if another banner is available to be shown, that banner is simply drawn on top of the fallback banner.  In this way, I don't need to constantly load/reset the fallback banner.

I have seen the "purple banner bug" appear occasionally, but it's always been the result of attempting to load a corrupted png into an Actor.   I have always resolved it by getting a new copy of the corrupted png. At any rate, the 12 Simply Love fallback banners are loaded appropriately in this theme; the issue you're seeing is unrelated to them.

Tell me more:
* What operating system are you using?
* What version of SM5?
* Is your copy of Simply Love completely up to date?
* Can you copy the tags from your file of *D - Try To Star Gradius III* and paste them here?  Additionally, list the contents of the particular song directory.  Providing a link where I can download the zipped song directory would also work.

As it stands, I'm unable to predictably reproduce this bug.

**Comment by dguzek** [comment]
Fixed by d7996d06001724cb4b6bd4f4202ac2f033ee46ed.
