### ISSUE TITLE
feature idea: fast user profile switching in songwheel

### ISSUE THREAD

**Issue by RodentVienna** [dguzek/Simply-Love-SM5#227]
every player who plays in a group with more than 2 people knows the hassle of trashing precious gameplay time for loading a different players profile.
- exiting the game
- press start
- select profile, select game, select game mode
- load songwheel

a feature for fast-user-profile-switching would consist of
- a songwheel option entry to quickly change to a different or unload a player profile
- entire reloading of the user preferences of the newly loaded profile (hello #225 #226)

this would allow for gameplay sessions with more than 2 players to be much more fluid

**Comment by RodentVienna** [comment]
while this looks feasible to be a theme-specific featue for Simply Love SM5, it may at some stage become part of the sm5.3-engine Team Rizu is working on. It may make sense to align with Team Rizu in this case.

**Comment by natano** [comment]
I WANT THIS! I didn't have a chance to look into this myself yet, except discussing a few ideas how to do it. If someone wants to step up creating a PR that implements it in a reasonable way that might speed up the feature being available. :)

**Comment by RodentVienna** [comment]
happy anniversary for this feature idea :)

i haven'theard anything news from sm5.3 team for this to be part of the engine. any chance some quirks can be done in simply love?

am i solely the only one on the planet (besides natano) wanting thi desperately? :)

**Comment by teejusb** [comment]
I think this is done with the ITGmania changes. @natano should we close?

**Comment by RodentVienna** [comment]
yes! shared my gratitude to natano on discord already. finally. this
feature is a godsend! thank you so much guys. now i can sesh with people in
peace :) (i briefly tested it, and it works great)

teejusb ***@***.***> schrieb am Di., 14. Juni 2022, 22:56:

**Comment by teejusb** [comment]
One thing to note. There is currently a bug with ScreenEvalSummary when profile switching is used. Check out https://github.com/Simply-Love/Simply-Love-SM5/issues/396 for details. Will be fixed next release though!
