### ISSUE TITLE
adding a dash into profile name through manage local profiles closes menu

### ISSUE THREAD

**Issue by ojsl1** [dguzek/Simply-Love-SM5#230]
This happens on linux, stepmania 5.1 and simply love 4.9.1. I'm not sure if this is intentional or not, however the popup menu goes white after trying to rename a profile again. The white menu returns to normal after you exit and re-enter the manage profiles menu.

![Screenshot_20201207_204946](https://user-images.githubusercontent.com/10965741/101392109-013b1600-38ce-11eb-98b7-45fca5b2e9b6.png)

I wouldn't normally mind this, but after seeing quietly-turning has a dash on their name on the image at the simply love documentation [here](https://github.com/Simply-Love/Simply-Love-SM5/blob/401d264abd358bad9a224ae9132c3e960ed8b399/Other/Documentation/ProfileAvatars-README.md), i'm guessing this isn't normal behavior?

**Comment by natano** [comment]
This happens because the dash is mapped to the back button for P2 by default. The white square also appears after backing out of the rename dialog with ESC (default back button for P1). It's definitely a bug.

**Comment by natano** [comment]
I created a PR for stepmania to remove the default key binding for the hyphen key: https://github.com/stepmania/stepmania/pull/2083

**Comment by natano** [comment]
White popup fixed on the beta branch.
