### ISSUE TITLE
Autoplay bug? Replace F8 autoplay and put it as option in song modifiers menu. 

### ISSUE THREAD

**Issue by Chineko-Koizumi** [dguzek/Simply-Love-SM5#235]
After quading a song I recived 0% and D 
![2020-12-13_222446](https://user-images.githubusercontent.com/48492992/102024627-7b1e4400-3d93-11eb-85b5-e9f5e6b73632.jpg)

![2020-12-13_222341](https://user-images.githubusercontent.com/48492992/102024635-85404280-3d93-11eb-9fd1-3b648a727ebe.jpg)

**Comment by teejusb** [comment]
Hmm this looks a lot like Autoplay

**Comment by Chineko-Koizumi** [comment]
> 
> 
> Hmm this looks a lot like Autoplay

I thought that was an easter egg but really got D after this :/

**Comment by Chineko-Koizumi** [comment]
I checked how to turn on autoplay and I had it on, however I was able to play whole chart normally then got it on, how? I think about change that issue from bug to future: removing autoplay with key and replace that with option from song modifier menu.

**Comment by teejusb** [comment]
I believe enabling/disabling Autoplay is built into the game and not part of the theme. My assumption is you might have hit the F8 key (maybe when trying to enable something else like the clap).

**Comment by Chineko-Koizumi** [comment]
I played it on pad, and I used only ESC and ENTER 😔.

**Comment by Chineko-Koizumi** [comment]
NVM I did it today  XD
![2020-12-14_222244](https://user-images.githubusercontent.com/48492992/102137379-0a425f00-3e5b-11eb-8cc1-cd1f09f61be2.jpg)

**Comment by natano** [comment]
I'm closing this ticket, autoplay was probably turned on by accident.

@Chineko-Koizumi In case you find a reliable way to turn on autoplay that does not involve pressing F8, please let us, that would probably be a bug.
