### ISSUE TITLE
Blurry banners

### ISSUE THREAD

**Issue by camsta4** [dguzek/Simply-Love-SM5#24]
The fix implemented for #22 has resulted in blurry banners shown on all screens except ScreenSelectMusic. Using LoadBanner(), the banners are high quality, but LoadFromCachedBanner() results in blurry ones.

**Comment by dguzek** [comment]
This should be resolved by 73ab3119afd06f5dbe8e56a5d765b7da4cbe6f7e.  Can you please test and comment, @camsta4?

**Comment by camsta4** [comment]
All fixed, banners are full res and the issue in #22 is still resolved. :+1:
