### ISSUE TITLE
[issue] No longer possible to access the game's options

### ISSUE THREAD

**Issue by rdlf4** [dguzek/Simply-Love-SM5#250]
Hello there. New to this theme, after playing with the default SM5 for nearly three years.
So far I like how colorful and vibrant this theme looks, but I have this issue that I always had to adjust the game's settings like the speed of the arrows (C700), the note skin I want to play with and the direction of the arrows (right, left, shuffle, etc).
While I couldn't find the latter for this theme (I believe it's hidden somewhere, but I couldn't manage to find it yet), Simply Love behaves weird when I'm trying to exit the game. No, not from a technical perspective -- it's just that it thinks it's an arcade machine, displaying the best scores and stuff, something StepMania default never did. And I wanted to change that. Digging into the settings, I managed to enable FREE MODE, which makes the OPTIONS disappear at the start screen of the game. And now I no longer have access to it.

Question is, is there a way to revert that? How can I access the options when free mode is enabled?
Finally, how do I set the orientation of the arrows? I don't mean to center it, but to determine which side of the screen the arrows come from (sometimes I do left, right, both and shuffle for additional challenge) but that seems not to be a thing in this theme.

Thank you in advance.

Regards.

**Comment by quietly-turning** [comment]
> Digging into the settings, I managed to enable FREE MODE, which makes the OPTIONS disappear at the start screen of the game. And now I no longer have access to it.

Home mode, Freeplay, and Coin Mode are core StepMania features universal to all themes.

You can read about the keyboard shortcut to toggle between them in the StepMania wiki: https://github.com/stepmania/stepmania/wiki/Key-Bindings-and-combinations#main-debug-menu

---

> the direction of the arrows (right, left, shuffle, etc).  While I couldn't find the latter for this theme (I believe it's hidden somewhere, but I couldn't manage to find it yet)

 Check **Advanced Modifiers**.
![Screen Shot 2021-01-25 at 11 52 00 PM](https://user-images.githubusercontent.com/1253483/105802053-72ab5280-5f68-11eb-8105-12369940c1e8.png)

**Comment by rdlf4** [comment]
Thank you for responding.
Is there a way to set the speed to C700 from the settings, so that the games saves that setting to the disk and I don't have to do that ever again before playing a song? (I know it's just once per gameplay, but still..)

**Comment by quietly-turning** [comment]
> Is there a way to set the speed to C700 from the settings, so that the games saves that setting to the disk and I don't have to do that ever again before playing a song?

Create a local profile.  Your modifiers will be saved to it and automatically applied if you don't visit the PlayerOptions menu before gameplay.

From the main title screen:
Options → Manage Local Profiles → Create Profile

**Comment by natano** [comment]
> [...] Simply Love behaves weird when I'm trying to exit the game. No, not from a technical perspective -- it's just that it thinks it's an arcade machine, displaying the best scores and stuff, [...]

You can disable the screens in Options -> Simply Love Options.

**Comment by natano** [comment]
Did that answer your questions, @rdlf4?
If yes I'll close the issue.

**Comment by rdlf4** [comment]
Yes, that worked out for me. Creating a profile saves my settings, no longer have to mess with them every gameplay.
F3 and 1 did the trick to change the game mode at start screen. Niiice.
Thanks a lot @quietly-turning! Closing the issue as all questions have been answered.
