### ISSUE TITLE
Feature Idea: Add a significant digit to mean timing error on results screen (Xms -> X.Xms)

### ISSUE THREAD

**Issue by cchike** [dguzek/Simply-Love-SM5#253]
It seems like the mean timing error would be quite a bit more useful/descriptive if it showed one more significant digit (Xms -> X.Xms). This is because, for example, a mean timing error of 4.6ms is actually a lot better than 5.4ms but they would both show up as 5ms mean timing error.

**Comment by teejusb** [comment]
I think a nice approach to this is to just add the significant digit only in cases where the metrics are < 10ms. This way we *mostly* preserve the space utilization (we add a period) and get additional info when it seems to be worthwhile.

**Comment by quietly-turning** [comment]
> This way we *mostly* preserve the space utilization

If the existing layout is kept, space can become an issue with SL's support for multiple languages.  If anyone works on this and/or #254, take localization layout into consideration! :)

**Comment by quietly-turning** [comment]
This has been implemented by pull request #290.
