### ISSUE TITLE
Feature Idea: Add "Max Timing Error" (i.e. all steps <= Xms)

### ISSUE THREAD

**Issue by cchike** [dguzek/Simply-Love-SM5#254]
Max Timing Error = the greatest ms error out of all your steps. For example, in the context of a quad, the greatest allowed Max is 23ms. Having this metric no longer limits your FC type to just 15ms quints and 23ms quads, etc. For example, seeing Max = 20ms means you actually did slightly better than a quad, and seeing Max = 24ms means you were very close to getting a quad. Seems like this metric could be added in the same row as Mean/Median/Mode. If not, I think Mode could probably be replaced because it doesn't seem that useful

**Comment by quietly-turning** [comment]
>  I think Mode could probably be replaced because it doesn't seem that useful

Out of genuine curiosity, do you find median to be useful?  I guess #253 suggests that you find mean helpful (or at least interesting?).

My original design for the offset histogram pane did not include mean, median, or mode (the histogram was intended to help new players find an appropriate scroll speed), and I've never really understood how knowing those values helped.

**Comment by teejusb** [comment]
I wanted to chime in and say that my personal sentiment is that we should at least have Mean + Std Dev as two of the metrics displayed. Mean would tell you how early/late one was, and std dev would tell one about the spread around the mean. It's similar to the existing mean timing error, except a more "true" metric of the normal distributions we expect to see. I would even say to replace the existing mean timing error in favor of std dev. Mode and Median I don't find particularly interesting/useful.

**Comment by cchike** [comment]
> > I think Mode could probably be replaced because it doesn't seem that useful
> 
> Out of genuine curiosity, do you find median to be useful? I guess #253 suggests that you find mean helpful (or at least interesting?).
> 
> My original design for the offset histogram pane did not include mean, median, or mode (the histogram was intended to help new players find an appropriate scroll speed), and I've never really understand how knowing those values helped.

The mean is referenced a lot when determining how “good” one’s overall timing was. Note that this mean is different than the true mean (which would be a better metric than Median, explained below)

> I wanted to chime in and say that my personal sentiment is that we should at least have Mean + Std Dev as two of the metrics displayed. Mean would tell you how early/late one was, and std dev would tell one about the spread around the mean. It's similar to the existing mean timing error, except a more "true" metric of the normal distributions we expect to see. I would even say to replace the existing mean timing error in favor of std dev. Mode and Median I don't find particularly interesting/useful.

This is a good idea. Right now, the “Mean” is the average of the absolute distance from 0, so if your steps were -4,-4,4,4, your Mean would be 4ms. If the absolute value was removed, we’d have a Mean of 0ms which kinda serves the same purpose as Median. Standard deviation would then become the measure of how “tight” the players timing was. That being said, I still think average distance from 0ms error, i.e. Mean(|ms error|), is a good metric for directly comparing different scores to each other. Therefore, I’d suggest including all 3 of True Mean, Standard Deviation, and Mean(|ms error|). This is, of course, in addition to Max Timing Error.

**Comment by quietly-turning** [comment]
Thanks for responding, @teejusb and @cchike.  It's always interesting for me to consider how people play the game. :)

**Comment by quietly-turning** [comment]
Is this something you'd be interested in working on and submitting as a pull request, @cchike?  

Your write-up here shows you have good grasp what you'd like to see implemented, and I'm sure the current project maintainers could help point you to the right file. 🙂

**Comment by cchike** [comment]
I could try. Like you said, I would need to know where to start though

**Comment by cchike** [comment]
Taronuke implemented this and #253 last night. So should we close these?

**Comment by teejusb** [comment]
Added in v5.2.0.
