### ISSUE TITLE
SimplyLove doesn't properly detect Stepmania version built from source

### ISSUE THREAD

**Issue by Hay1tsme** [dguzek/Simply-Love-SM5#266]
As discovered in #258 using a built-from-source version results in a Stepmania version string of "Stepmania 5.1-UNKNOWN" which trips the 5.3 protections, causing the skin to not load. Adding `version = version:gsub("-UNKNOWN","")` to line 63 of SL-SupportHelpers.lua appears to solve the issue, but I figured I'd report this anyway.

**Comment by quietly-turning** [comment]
Related:
https://github.com/Simply-Love/Simply-Love-SM5/pull/186
https://github.com/stepmania/stepmania/pull/1987

**Comment by Hay1tsme** [comment]
Figured out the -Unknown gets added on, even with git on my path, because I downloaded the zip file instead of using git clone.

**Comment by natano** [comment]
This is fixed on the beta branch (see 70c525084). Thanks for the report, @Hay1tsme!
