### ISSUE TITLE
Songs not showing and stuck on ITG selection wheel.

### ISSUE THREAD

**Issue by h4ckd0tm3** [dguzek/Simply-Love-SM5#270]
So since yesterday I am getting this view:
![Music wheel](https://i.imgur.com/uYvxf5t.png)

and when closing the group I only see 2 of my song groups out of many.
Already tried changing it again to IIDX in the Settings but didn't make a difference.

Already tried reinstalling and cleaning the Appdata Directory.

**Comment by quietly-turning** [comment]
It looks like you're in Casual Mode and that it is working as intended.

You can read more about Casual Mode in the CasualMode-README that comes with Simply Love in the `./Other/Documentation` folder, or on GitHub here: https://github.com/Simply-Love/Simply-Love-SM5/blob/release/Other/Documentation/CasualMode-README.md

**Comment by h4ckd0tm3** [comment]
Thank you, worked.
