### ISSUE TITLE
Improper UTF-8 handling in screenshot names

### ISSUE THREAD

**Issue by mglch** [dguzek/Simply-Love-SM5#279]
Screenshots created by Simply Love apparently contain the first 10 bytes of the song title, even if the 10-byte boundary falls in the middle of a UTF-8 character. This can result in invalid UTF-8 sequences in the resulting filename.

For example:

```
Neko Neko☆Super Fever Night
```

gets shortened to: 

```
Neko Neko�
```

because the "☆" character is 3 bytes long in UTF-8.

The string shortening function should be made UTF-8 aware, either by cutting 10 characters (instead of 10 bytes), or by making sure that invalid UTF-8 sequences are removed from the end of the output.

**Comment by quietly-turning** [comment]
Thanks for reporting this, @mglch.

There's no obligation for you to respond to this, but—how did you learn about character encoding (enough to be able to identify the nature of this issue)?  

Was it a topic you studied in school, perhaps for a particular class?  Was there a particular explanation or practical exercise that helped you comprehend it?  What was your technical background at the time you were able to understand it?

The explanations and tutorials I've found on character encodings have always seemed beyond my comprehension.  I've never been able to understand what they meant, and I'm sure this deficit in my knowledge directly led to bugs like this in Simply-Love-SM5.

**Comment by quietly-turning** [comment]
This should be resolved by pull request #288.
