### ISSUE TITLE
Name entry has background layer twice

### ISSUE THREAD

**Issue by kyzentun** [dguzek/Simply-Love-SM5#28]
The hearts in the background of the name entry screen seem much thicker than anywhere else, as if the background layer is loaded twice for some reason.
http://i.imgur.com/2RuV17n.jpg

Also, the summary screen does not correctly handle the case where more than 5 songs were played.  This happens when the songs per credit is set to 5 and the player earns extra stage (which is enabled by a preference).
http://i.imgur.com/X9PMypr.jpg

**Comment by dguzek** [comment]
The "double hearts" on NameEntry matches hurtpiggypig's original design.

The summary screen should handle n songs by allowing players to scroll through the results using menu buttons via metric-defined input codes: https://github.com/dguzek/Simply-Love-SM5/blob/master/BGAnimations/ScreenEvaluationSummary%20overlay/default.lua#L18-L35

I agree that it could definitely stand to be re-written to use a sick_wheel, but I don't really have the time right now.

**Comment by dguzek** [comment]
I don't think either of these issues are actually issues, so I am closing this.  See my previous comment, if necessary.
