### ISSUE TITLE
No ImmediateContinue?

### ISSUE THREAD

**Issue by kwokrobyn0** [dguzek/Simply-Love-SM5#280]
I'm on Simply Love 4.9.1. I'm using project moondance's version of StepMania. For some reason, there is no ImmediateContinue option for fail type. 
<img width="631" alt="Screen Shot 2021-04-06 at 7 35 36 PM" src="https://user-images.githubusercontent.com/63574844/113705082-97156f00-970f-11eb-965c-893782817053.png">

**Comment by natano** [comment]
I think Outfox just renamed it to "Delayed". Does that option do what you wnat?

**Comment by kwokrobyn0** [comment]
Yeah, I realized...thank you
