### ISSUE TITLE
combo zoom?

### ISSUE THREAD

**Issue by arceuss** [dguzek/Simply-Love-SM5#283]
i noticed that the combo number never zooms in
was it removed or something

**Comment by teejusb** [comment]
The combo zooming "feature" was removed in April 2019 in the commit here:
https://github.com/Simply-Love/Simply-Love-SM5/commit/ef0b64ecb1f16efa420e122856fe1a43dbab461d#diff-0549463bede64c2991bea366d31494bc6606d67800abbd319234dcb1c64e1fac

If you'd like you can reinstate it by doing the reverse of that commit on your own personal setup.
