### ISSUE TITLE
whatever is going on with my avatar

### ISSUE THREAD

**Issue by arceuss** [dguzek/Simply-Love-SM5#285]
![image](https://user-images.githubusercontent.com/28229451/115930941-8b33e780-a447-11eb-93f2-ace554ecc162.png)
i resized it using mspaint if that helps

**Comment by arceuss** [comment]
and its on the gs branch using outfox

**Comment by natano** [comment]
This should have been fixed with commit https://github.com/Simply-Love/Simply-Love-SM5/commit/552216811035b660237ee4a0107d3137727e2896 on the beta branch.
