### ISSUE TITLE
question: where are judgment commands located

### ISSUE THREAD

**Issue by arceuss** [dguzek/Simply-Love-SM5#293]
im trying to make the animations or whatever theyre called the same as itg2 but theyre not in metrics.ini so idk where they are

**Comment by teejusb** [comment]
`Graphics/Player judgment.lua`

**Comment by arceuss** [comment]
> 
> 
> `Graphics/Player judgment.lua`

how would i make each judgment have its own animation cuz it just seems they all use the same one

**Comment by teejusb** [comment]
`param.TapNoteScore` tells you the judgment. You just create an if statement and animate it however you want to.

**Comment by arceuss** [comment]
![image](https://user-images.githubusercontent.com/28229451/117516091-50f13c80-af55-11eb-82f7-8d7618600d5c.png)
is this right idk lua

**Comment by arceuss** [comment]
> 
> 
> `param.TapNoteScore` tells you the judgment. You just create an if statement and animate it however you want to.

still dont get it

**Comment by arceuss** [comment]
i still dont get it am i poopy brain or something

**Comment by arceuss** [comment]
> 
> 
> `param.TapNoteScore` tells you the judgment. You just create an if statement and animate it however you want to.
can you give an example
i wanna make a fork of this theme with itg2 related elements

**Comment by arceuss** [comment]
nvm i just made everything sprite:zoomx(1.3):zoomy(1.7):decelerate(0.1):zoom(1):sleep(1):accelerate(0.2):zoom(0):glowshift():effectperiod(0.05):effectcolor1(1,1,1,0):effectcolor2(1,1,1,0.5)
