### ISSUE TITLE
SongSearch - Option doesn't display due to OS Language

### ISSUE THREAD

**Issue by SimplyViper16** [dguzek/Simply-Love-SM5#300]
**[*Stepmania 5.0.12*]**
**[*Simply Love 5.0.0*]**

Hi! I was super happy to checkout the new song search feature, but the option wouldn't showing... Looking at the code, I've found the reason why!

Looking at _BGAnimations/ScreenSelectMusic overlay/SortMenu/default.lua_:
![image](https://user-images.githubusercontent.com/10159143/117729052-92e6e080-b1ea-11eb-9d81-fe16ac98e4e2.png)

The issue is caused by INPUTMAN:GetDescriptions(): I've Windows in italian and then the result of INPUTMAN:GetDescriptions() is "Tastiera" instead of "Keyboard" (Tastiera means actually Keyboard, btw).
I was thinking to remove the if and always shown the option (and then make the pull request), but maybe you've got a better idea, even because I've read it's a requirement having the keyboard connected, so this is the reason I've prefered to open an issue.

For any further information, if you need, I'm here!
Thank you!
Viper

**Comment by teejusb** [comment]
Ah! I did not know about the language issue! I don't think removing the if is correct because it doesn't make sense to show that option if people don't have a keyboard connected. I think you can add a `or (THEME:GetCurLanguage() == "so" and device == "Tastiera")` clause to the condition.

**Comment by SimplyViper16** [comment]
Sorry the title was wrong!! The issue is caused directly by the Operating System, which is in italian, so all the devices description are that language. In fact, I'm using the theme always in English.
Maybe the problem may occur for all OS not in english(?)

**Comment by teejusb** [comment]
Ah I see! That's an even more interesting problem then. I'll have to see how the game obtains the device description and will need to figure out the best course of action. It might just be a whitelist of "acceptable keyboard strings".

**Comment by teejusb** [comment]
I think our solution will be to just move "Keyboard" options to the operator menu and then the machine owner can figure out if they want to enable/disable the option.

**Comment by natano** [comment]
In the next release there will be an option in the operator menu for turning keyboard features on or off. (see https://github.com/Simply-Love/Simply-Love-SM5/pull/313)
