### ISSUE TITLE
Português Brasileiro is not supported anymore

### ISSUE THREAD

**Issue by moruzerinho6** [dguzek/Simply-Love-SM5#303]
[The README states that Português Brasileiro is still supported by Simply Love](https://github.com/Simply-Love/Simply-Love-SM5#language-support) which is incorrect since I stopped doing its translation and the [new additions](https://github.com/Simply-Love/Simply-Love-SM5/commit/6b48db4a17e0f9ba5f61f1c1217770850efb2c22#diff-6247c85c9d60c4b343a6bbffc6e71481643f9f9284b3f5151304c1252db0b1c6) are making it more English than Portuguese which could be solved by maybe using something like Google Translator.

It would be better to not state was officially supported anymore and not required but a request myself please remove it as I'm not happy with its quality.

**Comment by natano** [comment]
I added a note to the README that the translation is incomplete and we are looking for a maintainer. We opted to not fully remove the translation to make future translators work easier.
