### ISSUE TITLE
Graph preview in songwheel breaks for DWI files

### ISSUE THREAD

**Issue by ghost** [dguzek/Simply-Love-SM5#305]
The song measure preview graph in the songwheel overflows over the song names when a DWI file is hovered over.

When switching between difficulties for DWI files in this mode, the graph isnt updated

Tested with A and V from keyboard megapack

**Comment by teejusb** [comment]
Technically I don't think we support parsing DWI files (so it should just be empty). Can you link a specific affected song so I can look into it?

**Comment by ghost** [comment]
Any song with only a DWI (no SM, SSC) has a broken graph in the song wheel.

I cannot find a link to KMP, but this pack has some files with DWIs only: https://search.stepmaniaonline.net/pack/id/350
"At Least I Can Say I Tried | Cex"
"Attack"
"Battle Ax"
etc

**Comment by natano** [comment]
With PR https://github.com/Simply-Love/Simply-Love-SM5/pull/314 this is fixed. Please note that we still don't support chart analysis for dwi files, but now we don't display incorrect information anymore.

Thanks for reporting the issue, @s34nvideos!
