### ISSUE TITLE
Pad input on results screen for doubles visually off

### ISSUE THREAD

**Issue by ghost** [dguzek/Simply-Love-SM5#306]
The pad input dialog on the results screen when playing  doubles is visually off to the left

Tested p1 side doubles play.
Picks song. Hold exit button to quit to results screen. Scroll across to pad input

**Comment by natano** [comment]
@s34nvideos I'm not sure if I understand what you mean. Is this the screen?
![Screenshot_20210523_150949](https://user-images.githubusercontent.com/27127/119261731-f56fb180-bbd8-11eb-887e-543cb35b6aae.png)
I don't see anything wrong with it, but I'm probably misunderstanding.

**Comment by ghost** [comment]
The pad input screen/dialog only seems to appear on a machine. The dialog is missing on my PC. I'm not sure what kind of check it does. 

The dialog looks like 'Test Input' where there is an image of a dance pad and you can test your input. Its on the results screen. So from the image you posted, scroll left or right to view it.

I can provide an image for clarify if still needed. I just didnt want to turn the cab on lol

**Comment by natano** [comment]
Hm, I think I've never seen that dialog :exploding_head:
Do you have an unmodified version of SL running on your cab? I think I'll need a screenshot, sorry

**Comment by teejusb** [comment]
![image](https://user-images.githubusercontent.com/5017202/119309306-fa595300-bc22-11eb-8cfe-d62dd10ff4ff.png)
He's talking about this. It shows up if you have OnlyDedicatedMenuButtons turned on (since otherwise you'd get stuck on that pane).

**Comment by teejusb** [comment]
![image](https://user-images.githubusercontent.com/5017202/119310120-2c1ee980-bc24-11eb-8e60-f0ffbfc79ade.png)

![image](https://user-images.githubusercontent.com/5017202/119310183-3f31b980-bc24-11eb-86be-ec68982f393a.png)

I'll push this fix which seems alright to me.

**Comment by teejusb** [comment]
Done :)
https://github.com/Simply-Love/Simply-Love-SM5/commit/f588d2197475cd71b6bbb0dc74ccb93cb1c32343

**Comment by ghost** [comment]
Nice!
You probably have enough folks, but I don't  mind volunteering for beta testing before anything is released in the future.

**Comment by natano** [comment]
Thanks for reporting the issue and for the testing offer, @s34nvideos!
