### ISSUE TITLE
"counts as X rounds" covers Peak NPS

### ISSUE THREAD

**Issue by Horsey-** [dguzek/Simply-Love-SM5#308]
I noticed this while looking into merging my fork with the new SL version. I know that you guys want to preserve the theme aesthetics as much as possible, but it's now starting to really get crowded on ScreenSelectMusic. Maybe consider ditching ScreenSelectMusic header and incorporating that information into the information "card" something like the second image (mock-up); not so radical as a complete redesign as seen in the image, but just condense the information into that card below the banner?
![Screen Shot 2021-05-14 at 10 51 57 AM](https://user-images.githubusercontent.com/5679966/118309764-92786f00-b4a2-11eb-8b3c-67560bbb5e3f.png)

![Simply-Love-Song-Selection-Concept3](https://user-images.githubusercontent.com/5679966/118310354-5b568d80-b4a3-11eb-9d35-9b4adece0082.png)

**Comment by Horsey-** [comment]
Here's how I solved it: I prepended the PeakNPS readout to the stream readout. 

![Screen Shot 2021-05-18 at 11 14 38 PM](https://user-images.githubusercontent.com/5679966/118764744-de267200-b82e-11eb-8cf0-33834ce3e820.png)

**Comment by natano** [comment]
This is fixed with PR https://github.com/Simply-Love/Simply-Love-SM5/pull/316.

Thanks for reporting the issue, @Horsey-!
