### ISSUE TITLE
(Untested) patch for some issues with Subtractive Scoring

### ISSUE THREAD

**Issue by OmnipotentEntity** [dguzek/Simply-Love-SM5#31]
This is my first time programming in SM5 Theme world.

I had noticed a few problems with Subtractive Scoring, the first is if you avoid a mine the score goes to percentages.  The second is until you go to percentages players share excellents and the percentage state.

Here's a patch that ought to fix it.  However, I won't be able to actually test it until at least tomorrow evening, so I'm going to send it now.

    diff --git a/BGAnimations/ScreenGameplay overlay/SubtractiveScoring.lua b/BGAnimations/ScreenGameplay overlay/SubtractiveScoring.lua
    index d353473..76ebd19 100644
    --- a/BGAnimations/ScreenGameplay overlay/SubtractiveScoring.lua	
    +++ b/BGAnimations/ScreenGameplay overlay/SubtractiveScoring.lua	
    @@ -1,4 +1,5 @@
     local player = ...
    +local pn = ...
     
     if not SL[ ToEnumShortString(player) ].ActiveModifiers.SubtractiveScoring then
      return false
    @@ -14,11 +15,11 @@ else
     
      -- flag to determine whether to bother to continue counting excellents
      -- or whether to just display percent away from 100%
    -	local received_judgment_lower_than_w2 = false
    +	local received_judgment_lower_than_w2 = {false, false}
     
      -- these start at 0 for each new song
      -- FIXME: What about course mode?
    -	local w2_count = 0
    +	local w2_count = {0, 0}
      local judgment_count = 0
      local tns
     
    @@ -35,14 +36,14 @@ else
        end,
        SetCommand=function(self, params)
     
    -			if tns == "W2" and not received_judgment_lower_than_w2 and w2_count < 10 then
    +			if tns == "W2" and not received_judgment_lower_than_w2[pn + 1] and w2_count[pn + 1] < 10 then
              -- increment for the first ten
    -					w2_count = w2_count + 1
    +					w2_count[pn + 1] = w2_count[pn + 1] + 1
              -- and specificy literal W2 count
              self:settext("-" .. w2_count)
     
    -			elseif tns ~= "W1" then
    -				received_judgment_lower_than_w2 = true
    +			elseif tns ~= "W1" and tns ~= "AvoidMine" then
    +				received_judgment_lower_than_w2[pn + 1] = true
     
            -- if not W1 or W2, specify percent away from 100%
            local pss = STATSMAN:GetCurStageStats():GetPlayerStageStats(player)
    @@ -57,4 +58,4 @@ else
          end
        end
      }
    -end
    \ No newline at end of file
    +end

**Comment by dguzek** [comment]
You know, it was brought to my attention that Subtractive Scoring had issues, and I looked into it briefly, but got caught up in UPSRT theming at the time and completely forgot until now.  

Thanks for the patch!  I'll check it out later today.

**Comment by OmnipotentEntity** [comment]
Ah nice, I like that better.  Didn't know that was possible.

**Comment by OmnipotentEntity** [comment]
Another patch, this one to fix hold excellents from being double counted.

    diff --git a/BGAnimations/ScreenGameplay overlay/SubtractiveScoring.lua b/BGAnimations/ScreenGameplay overlay/SubtractiveScoring.lua
    index 7b779ac..df37b14 100644
    --- a/BGAnimations/ScreenGameplay overlay/SubtractiveScoring.lua	
    +++ b/BGAnimations/ScreenGameplay overlay/SubtractiveScoring.lua	
    @@ -29,15 +29,17 @@ else
     				:diffuse(color("#ff4cff")):zoom(0.35)
     				:xy( x_position + (notefield_width/2.9), _screen.cy )
     		end,
    +
     		JudgmentMessageCommand=function(self, params)
     			if player == params.Player then
     				tns = ToEnumShortString(params.TapNoteScore)
    +        tnt = ToEnumShortString(params.TapNoteType)
     				self:queuecommand("SetScore")
     			end
     		end,
    -		SetScoreCommand=function(self, params)
     
    -			if tns == "W2" and not received_judgment_lower_than_w2 and w2_count < 10 then
    +		SetScoreCommand=function(self, params)
    +			if tns == "W2" and tnt == "Tap" and not received_judgment_lower_than_w2 and w2_count < 10 then
     					-- increment for the first ten
     					w2_count = w2_count + 1
     					-- and specificy literal W2 count
    @@ -59,4 +61,4 @@ else
     			end
     		end
     	}
    -end
\ No newline at end of file
+end

**Comment by dguzek** [comment]
I won't have time to test this in the next twenty-four hours, likely.  Will you?  :)

**Comment by OmnipotentEntity** [comment]
Yeah, I'll try to test it when I get home.

**Comment by OmnipotentEntity** [comment]
You seem to be using tabs, is this a conscious choice, or an artifact of your text editor?  (ie, would you prefer if I used tabs or if I converted to spaces?)

**Comment by dguzek** [comment]
I don't have strong feelings on the issue of tabs/spaces.

**Comment by OmnipotentEntity** [comment]
The patch absolutely does not work, and I'm trying to figure out why, but I'm having some difficulty because this is the first time I've ever attempted themeing.

As far as I'm aware, what's going on is both the hold head and the hold tail are being marked with the W2 judgement.  This is causing the double counting perhaps?

My problem is I'm not sure what's available in the params, and I can't find either documentation or the area of the SM code that sets it.  I was trying to look at the note type but it doesn't seem to be in there.  And I can't figure out where my stepmania logs are on this computer (OSX).

I'll try on one of my Linux boxes later this weekend.  But it's also V-Day time, so I have personal responsibilities, etc.  I'll get it sorted as soon as I'm able.  I'm sure you're so familiar with this that it's probably painful to watch me fumble around.  So, sorry about that.

**Comment by dguzek** [comment]
StepMania logs on OS X are easiest to view with the _Console_  application that came with your Mac.

There are a couple means of debugging in SM5.  The easiest might be to use the utility function `SM()` which is really just a shorthand notation for `SCREENMAN:SystemMessage()` with the added functionality of recursively printing tables to the screen.  It also logs the same text to your log.txt file.

So, you would just call `SM(params)` inside the *JudgmentMessageCommand* function to have the contents of the params table printed to the screen and logged to log.txt.

As a heads up, I document this aspect of StepMania theming here: <http://dguzek.github.io/Lua-For-SM5/Singletons/SCREENMAN.html> as part of my Lua for SM5 guide.

**Comment by OmnipotentEntity** [comment]
Tested, pull request #33
