### ISSUE TITLE
Density Graph on Song Select will go out of its' frame for some songs

### ISSUE THREAD

**Issue by AdverbReverb** [dguzek/Simply-Love-SM5#319]
This will also occur in the results screen to the same effect, but have attached a picture of the song select wheel and what the issue looks like:

![Density Graph](https://user-images.githubusercontent.com/84732064/119377082-1399e800-bc93-11eb-9700-e4804960443a.jpg)

It does appear that when this happens the Density information also copies the info from the song it loaded from prior to scrolling to the song it will glitch on.

As a workaround is there a way to disable this feature and/or the Tech Analyzer entirely at the moment?

**Comment by natano** [comment]
This happens for charts that are in an unsupported format (i.e. not .sm or .ssc). I added a commit (https://github.com/Simply-Love/Simply-Love-SM5/commit/530a458682c6aa8eef5a2c116b13752013785787) to the beta branch to handle that case correctly. On the beta branch (and the next release) the theme will just not display the NPS graph in that case.

As a workaround you can update to the beta branch until we roll a new release, @AdverbReverb.
