### ISSUE TITLE
Feature Request: Sticky titles on song groups

### ISSUE THREAD

**Issue by fent** [dguzek/Simply-Love-SM5#32]
When scrolling through list of songs, would be useful to be reminded what group is being browsed. 

![screen shot 2016-02-14 at 12 37 39 am](https://cloud.githubusercontent.com/assets/933490/13032096/2839ac6a-d2b4-11e5-9979-b254095a232c.png)

![screen shot 2016-02-14 at 12 37 55 am](https://cloud.githubusercontent.com/assets/933490/13032097/2e1ce0e8-d2b4-11e5-8b23-8de0d5bd09e6.png)

Tried looking myself where the list of packs/songs is drawn so I could take a shot at this, but couldn't find where.

**Comment by dguzek** [comment]
This is an interesting idea.  

Given that the theme currently uses the engine's MusicWheel, the only solution I can think of offhand would be a "smoke and mirrors" approach.  That is, keep a Quad positioned up at the top of the screen and have its visibility toggled on/off depending on the state of the MusicWheel.  Perhaps I can look into this some rainy afternoon.

An alternate solution would be to write a custom MusicWheel in Lua and define the behavior yourself.

**Comment by dguzek** [comment]
As I think about it more, I think this feature would likely confuse novice players, for whom I designed "Casual Mode" in the *GameModes* branch, which is soon to be merged with *master*.  Novice players very rarely comprehend the Groups/Songs hierarchy that SM enforces.

With that said, I still think this is a useful idea for other GameModes targeted at SM veterans.

**Comment by RodentVienna** [comment]
I have see horseyhorse implementing this in a fork of this repo. would you consicer looking at this? To me it seems good enough. I suggest a "Beginner" Mode" which is something like "Casual, Competitive, ECFA, Stomper", where this feature is not present. Or a Machine Option. Also for Songpacks with a lots of songs it sometimes could make sense to see the pack name.

**Comment by dguzek** [comment]
I am not interested in implementing this at this time for (at least) the reason I [discussed above](https://github.com/dguzek/Simply-Love-SM5/issues/32#issuecomment-205987646).
