### ISSUE TITLE
Add 🏃‍♂️ to Emoji font

### ISSUE THREAD

**Issue by zaneneuschuler** [dguzek/Simply-Love-SM5#332]
While working on a file for my next pack, I decided to mess around by adding emoji to the the title field to see what would happen. To my surprise, it worked!... Kinda. 

![Screenshot showing "Run Around The Character Code! X💨" instead of 🏃‍♂️💨"](https://zaneis.moe/ss/2021-06-20_20-27_12122.png )

As 🏃‍♂️ is in the default emoji/unicode character set, I feel like it would be a pretty easy addition, however I will admit I have no idea how to add it myself.

**Comment by teejusb** [comment]
SL has a very limited emoji set and we tend to just add a few at a time as needed. But that being said, it's actually pretty easy add as it just requires the spritesheet and ini file update. For example, https://github.com/Simply-Love/Simply-Love-SM5/commit/72008bdeab8c3367543b0e17be9a4a7506999b16

Maybe it might be worthwhile to just expand this file to encompass the entire default emoji set. Will look into it.

**Comment by natano** [comment]
:runner: :dash:
