### ISSUE TITLE
'Exit' button in options behaving differently than pressing 'Back'

### ISSUE THREAD

**Issue by celex3** [dguzek/Simply-Love-SM5#350]
When starting the game with Simply Love as the selected theme, or when selecting 'Exit' on the main Options menu, I am brought to the System Options screen and warned that Simply Love does not support the current version of my game. However, when I press back (bound to 'Esc' by default) I am sent to the main menu and play the game. 

I am running Stepmania OutFox (5.3) Alpha 4.11 on my M1 Macbook pro.

**Comment by natano** [comment]
The newest version of Simply Love (v5.0.1) supports OutFox alpha 4.11. Are you using an old version of the theme?

**Comment by celex3** [comment]
At the time of writing I was using the Simply Love (v5.0.1), but it looks like the newest build of OutFox (4.12.0) fixed this issue.
