### ISSUE TITLE
score bug

### ISSUE THREAD

**Issue by kaiten619** [dguzek/Simply-Love-SM5#353]
i get an 82.45 on a song but it says i fail and gave me an f. i don't think thatss accurate that should had given me an a-

**Comment by kaiten619** [comment]
![2022-01-15_025018](https://user-images.githubusercontent.com/22760371/149745053-851dfeda-5822-45a8-955f-cf6bdf6aab6f.jpg)

**Comment by natano** [comment]
What pack is this from? I would like to reproduce the issue.

**Comment by kaiten619** [comment]
> What pack is this from? I would like to reproduce the issue.

My Anime Collection R-T

**Comment by kaiten619** [comment]
im also using the latest project outfox if you want to know which stepmania im using

**Comment by teejusb** [comment]
I was told that in Outfox, "Charts now have their own length. It's needed for modes like BMS. It's likely that the song length now is slightly longer than the length of the chart."

This seems to cause issues with the way SL currently determines if a player has quit out of a song out early or not (which if you normally do then the theme fails you).

**Comment by kaiten619** [comment]
i don't quit out of songs at all. i usually finish the song no problem

**Comment by teejusb** [comment]
I'm saying there is logic in place to check /if/ someone quits out of a song early that depends on song length, which has been modified on OutFox.

**Comment by kaiten619** [comment]
my bad my bad. i hope there is a solution to this. i really do not want to go back to an old version of outfox

**Comment by kaiten619** [comment]
ok the bug got fixed at outfox 4.13
