### ISSUE TITLE
Casual mode's GetDefaultSong is not parsing group names entirely

### ISSUE THREAD

**Issue by JoseVarelaP** [dguzek/Simply-Love-SM5#359]
In some groups, the formatting of the string recieved to get the group name, which is obtained by performing the lookup from the `preliminary_songs` variable, and the gsub command is not cutting properly, and leaving residue.

There can be instances where it is not cut properly, and thus never having a proper value that can be used to search the items on the FindInTable function afterwards, leading to packs that are never found to be used as the Default Song.

Example (Song in question: `7guys1pack/RIP (Nhato Remix)`):
```
7guys1pack/RIP (Nhato Remix) -> 7guys1pack(Nhato Remix)
```

## The fix:

It's just a single line change, from 108 in `Setup.lua` from `ScreenSelectMusicCasual overlay`:
```diff
- local _group = prelim_song:gsub("/[%w%s]*", "")
+ local _group = prelim_song:match("(.*)/")
```

Here's an enviroment bench that showcases this too.
```lua
-- the segment can cut off from the text.
local prelim_song = "7guys1pack/RIP (Nhato Remix)"
print( "gsub: ".. prelim_song:gsub("/[%w%s]*", ""))
print( "match: ".. prelim_song:match("(.*)/") )
```

**Comment by natano** [comment]
I pushed a fix to the beta branch. Thanks for the report @JoseVarelaP!
