### ISSUE TITLE
PIU Menu Up/Down and Change Difficulty Broken

### ISSUE THREAD

**Issue by mpphan** [dguzek/Simply-Love-SM5#36]
Comparing default skin to this skin, I am unable to change difficulty in pump game mode. Default allows up left and up right to be able to change difficulty, but I cannot do it in SimplyLove skin. The test input shows that the menu up and down are broken as well. I am using default control scheme for the keyboard.

**Comment by dguzek** [comment]
Thanks for pointing this out.  It should be resolved as of the latest commit to the _GameModes_ branch.

As an aside, PIU support is pretty badly broken in this theme, in general.  Scoring is incredibly wrong and I'm unable to figure out why.

**Comment by mpphan** [comment]
Thanks for the quick turnaround. I can confirm that the GameModes branch fixes the change difficulty. The menu up and down seem to still be broken though, but it does not impact the gameplay as much. Thanks!

**Comment by mpphan** [comment]
Actually... I'm just mistaken on the test input screen. The top and bottom buttons look like they may actually be a select and back.
