### ISSUE TITLE
Can these changes please be made for future OutFox compatiblity?

### ISSUE THREAD

**Issue by JoseVarelaP** [dguzek/Simply-Love-SM5#374]
With the new release of OutFox (Alpha 4.14.0), certain changes are being made that will break compatibility again on current Simply Love.

- ### Product Family has changed back to Outfox, and dropped the 5.3 prefix to deal with Windows package signing.
Given this change, the theme will again block users from exiting the options menu, so a recomendation is to just include "OutFox" in the list of alllowed ProductID strings in `SL-SupportHelpers.lua`.
```lua
StepManiaVersionIsSupported = function()
     if type(ProductID) == "function" and ProductID():find("OutFox") then return true end
end
```
- ### The chart ending behaviour is returning for all modes, which will break Gave Up calculation in the theme
In `BGAnimations/ScreenGameplay overlay/FailOnHoldStart.lua`, the check for the Gave Up time will completely break given OutFox's method for the end time for the song now being based on the longest chart rather than the song's audio file. For this, a new function has been added that provides the same functionality called `GaveUp()`, which is available on the StageManager.
[A 5.1 version of the function is already up on the StepMania repository for use.](https://github.com/stepmania/stepmania/pull/2201)
```lua
-- We need a way to check if the player gave up before the song properly ended.
-- It doesn't look like the engine broadcasts any messages that would be helpful here,
-- so we do the best we can by checking the song position.

local af = Def.ActorFrame{
	OffCommand=function(self)
		local fail = STATSMAN:GetCurStageStats():GaveUp()
		-- local fail = (GAMESTATE:GetCurMusicSeconds() < GAMESTATE:GetCurrentSong():GetLastSecond())

		-- In course mode always fail if we're not already on the last
		-- song. If we are on the last song, then we fall back to the
		-- condition above.
		if GAMESTATE:IsCourseMode() then
			local course = GAMESTATE:GetCurrentCourse()
			if GAMESTATE:GetCourseSongIndex() + 1 < course:GetNumCourseEntries() then
				fail = true
			end
		end

		-- We have to fail both players as we stopped the song early.
		if fail then
			-- Let's fail the bots as well.
			for player in ivalues( GAMESTATE:GetEnabledPlayers() ) do
				local pss = STATSMAN:GetCurStageStats():GetPlayerStageStats(player)
				pss:FailPlayer()
			end
		end
	end,
}

return af
```

**Comment by SheepyChris** [comment]
Raising this issue once again since a minor release went through without the aforementioned patches.

**Comment by KyDash** [comment]
The fixes provided for the chart ending behavior actually results in error: `STATSMAN:GetCurrentStageStats()` doesn't exist, but `STATSMAN:GetCurStageStats()` is what's meant to be used instead

**Comment by JoseVarelaP** [comment]
Ah whoops yeah, it's a typo.

**Comment by natano** [comment]
The changes are available in the beta branch now and will be included in the next release (see PR https://github.com/Simply-Love/Simply-Love-SM5/pull/375).
Thanks for the heads up and the GaveUp() backport!
