### ISSUE TITLE
emptying a sort by difficulty category with ctrl+backspace crashes stepmania

### ISSUE THREAD

**Issue by ojsl1** [dguzek/Simply-Love-SM5#377]
SM: 5.1-git-6510496
SL: 5.1.1
OS: Arch Linux 64bit on <s>5.16.16 kernel with unloaded modules after</s> 5.17.1 <s>install</s>

Expected behavior: I vaguely remember SL having an -empty- message for empty categories, but I might be remembering wrong?

This doesn't happen on the default stepmania home theme (not sure about the older 5.0 legacy theme)
Crashes also on Waterfall Expanded 0.76, which i presume being a fork of SL means this is an old bug?

Attached stepmania crash report: [crashinfo.txt](https://github.com/Simply-Love/Simply-Love-SM5/files/8399766/crashinfo.txt), the same file in pastebin: https://pastebin.com/K3VmC8ce

**Comment by quietly-turning** [comment]
@ojsl1 – Can you provide step-by-step instructions to recreate this crash?

---

Notes for devs: <kbd>control</kbd> + <kbd>backspace</kbd> in ScreenSelectMusic is hardcoded in the StepMania engine to delete the current song from disk.  This feature was added to SM5.1-beta in https://github.com/stepmania/stepmania/commit/473974e52f82b8f05e0d9a067af810a48492c75e

**Comment by natano** [comment]
@ojsl1 Do you have step-by-step instructions how to reproduce? I was trying to reproduce it on latest 5_1-new, but the category just vanishes and SM keeps running. Could you maybe check if this also happens for you on the latest commit in 5_1-new too?

**Comment by natano** [comment]
Can not reproduce. Please reopen if there is new information.
