### ISSUE TITLE
skin not even working

### ISSUE THREAD

**Issue by kaiten619** [dguzek/Simply-Love-SM5#380]
not working the latest project outfox
![2022-04-07_173911](https://user-images.githubusercontent.com/22760371/162341356-88a3a446-6cd0-43bf-8c24-4f955dca6f04.jpg)

**Comment by natano** [comment]
The newest OutFox alpha is not supported in the current Simply Love release. You will have to use the beta branch until the next SL release. (OF changed the product identifier, that's why it needs code changes in the new version.)

**Comment by Coolaaron88** [comment]
Any word on when the next release of Simply Love is going to be?

**Comment by teejusb** [comment]
The newest version got released 3 days ago (v5.1.2), or do you mean the one after that?

**Comment by Coolaaron88** [comment]
> The newest version got released 3 days ago (v5.1.2), or do you mean the one after that?

Wow, completely missed that haha  Thank you for bringing that to my attention. Thats the info I needed :)
