### ISSUE TITLE
Game freezes going into screen gameplay

### ISSUE THREAD

**Issue by teejusb** [dguzek/Simply-Love-SM5#381]
Context: https://clips.twitch.tv/GloriousMildPassionfruitJebaited-Rb2S-Zd_zJRn5qEj 

In Simply Love (and also Waterfall) it seems like the game will freeze when trying to go into gameplay. The behavior seems similar to what happens when there's an infinite loop. I don't quite know what might be causing it, but since it happens in SL and WF, my guess is that it's related to the ScoreBox.

**Comment by natano** [comment]
Do you have an idea how to reproduce it?

**Comment by teejusb** [comment]
Not particularly. The only consistency is that it happens when going into Screen Gameplay.  Other reports:

https://discord.com/channels/165133532199387136/591847174883508224/963213635017142273 (requires being in the Stamina Nation discord, some more context around the post)
https://clips.twitch.tv/ArbitraryInventiveKittenOMGScoots-JyJO_7TNMwwRb91g
