### ISSUE TITLE
[ITGmania] ScreenEvaluationSummary nullifies scores when fast profile switching is used

### ISSUE THREAD

**Issue by teejusb** [dguzek/Simply-Love-SM5#396]
When you switch a profile, regardless of if you switch sides or not, or even if you are rejoining the same profile, the ScreenEvaluationSummary will fail to display your previous scores in the same set:

![image](https://user-images.githubusercontent.com/5017202/173622924-101102aa-b3bf-44b3-8bcc-f6fd6f474b2d.png)

My suspicion is that the issue is likely that when you unjoin a player it unloads it from memory. So even if you rejoin, it's still a different underlying object.
That would need an ITGmania change, but there's a way to handle it themeside by just storing the displayed data for the set.

**Comment by jenxness** [comment]
I'm looking into this :eyes: No ETA on the solution at the moment, but I have a rough idea where to look.
