### ISSUE TITLE
[ITGmania] Starting a DWI song breaks GrooveStats until reset

### ISSUE THREAD

**Issue by florczakraf** [dguzek/Simply-Love-SM5#407]
When one attempts to play a song that provides only a DWI file, GrooveStats features break for other songs in the future.

The issue can be reproduced on the package that was mentioned in the past, in the issue related to DWI files: https://github.com/Simply-Love/Simply-Love-SM5/issues/305#issuecomment-840751060.
It's sufficient to just start such a song and give up or fail. After getting back to the song wheel, GrooveStats features will be disabled. The only way I could find to reenable them was to quit back to the main menu.

I couldn't reproduce the issue with Stepmania and GrooveStats Launcher -- it works as expected, i.e. ignoring the DWI songs and still processing other songs.

Show Recent Errors (F3-F6-9) doesn't show any.  
I don't think there's anything useful in the log either but I'm attaching it for completeness: [log.txt](https://github.com/Simply-Love/Simply-Love-SM5/files/9057719/log.txt)

**Comment by natano** [comment]
Fixed. Thanks for the bug report, @florczakraf!
