### ISSUE TITLE
Arduino serial communication 

### ISSUE THREAD

**Issue by CuackDj** [dguzek/Simply-Love-SM5#417]
Question: is there a solution for recieve serial information, like for an arduino. So I can mod lights in response of what stepmania is doing. This thru sound or any function?

**Comment by teejusb** [comment]
StepMania/ITGmania has the SextetStream mechanism to do this. Check out the following:

https://github.com/stepmania/stepmania/blob/master/src/arch/Lights/LightsDriver_SextetStream.md
https://github.com/geefr/stepmania-linux-goodies

**Comment by CuackDj** [comment]
found this https://github.com/Tiny-Foxes/SM5-Arduino-Lighting, solve all m problem using an arduino for all your lights =)
