### ISSUE TITLE
Animated score graphs

### ISSUE THREAD

**Issue by djpohly** [dguzek/Simply-Love-SM5#42]
Just leaving this here so I remember to look into it.

In IIDX, the target score graphs fill up as you play to give a visual representation of how you compare to your target/high score so far.  I'm sure we could make this happen by hooking into something like NotesCrossed and scaling the target by the percentage of the chart's points that have gone by.

**Comment by dguzek** [comment]
Would you say that this issue has been resolved by your [pull request](https://github.com/dguzek/Simply-Love-SM5/pull/43)?

**Comment by djpohly** [comment]
Ah, yup. I guess "implements" isn't on their auto-close keyword list.
