### ISSUE TITLE
Feature request: visual indication for x-difficulty scale

### ISSUE THREAD

**Issue by maboesanman** [dguzek/Simply-Love-SM5#422]
I have custom charts on both difficulty scales, and was wondering what I could do to indicate which is which.

I was thinking of some sort of "x" icon in the corner of difficulty blocks, which is informed by searching up the folder tree for a "METERTYPE.txt" file, starting from the .scc/.sm file. If a song has a metertype file, or a pack has a metertype file, then that would set the meter type.

maybe the two meters are "x-difficulty" and "classic", indicated by an "x" or a "c" in the corner of the difficulty indicator, wherever it appears (song select, gameplay), and there is a simply love theme option for display style: "none, x-difficulty only, classic only, and both"

the METERTYPE files would be manually added to packs by the user if they want to use this feature, and the songs folder would have a METERTYPE.txt with the default. if this pattern catches on, other themes could incorporate, and pack makers could include a METERTYPE file.

thoughts? this feature may also make more sense as a module.

I've made an incomplete version of the feature that prepends a "." when the songdir or it's parent contains a file named "XMETER.txt" for personal use, though it overflows the container for meter >19 and only displays on the song select grid. I can work on getting that as a PR if it's worth seeing.

**Comment by natano** [comment]
We decided on not implementing this. Having a mechanism to distinguish between different scales would be nice, but that ship sailed many years ago. Now the ratings are all jumbled up already and noone is going to re-release all the old content with new metadata.

I encourage you to make a [module](https://github.com/Simply-Love/Simply-Love-Modules) for it though, so people who want this can use it to tag their own song collection.
