### ISSUE TITLE
Feature Request: Combo Lamps

### ISSUE THREAD

**Issue by eah1759** [dguzek/Simply-Love-SM5#432]
I would love some way to see your best combo type for a particular song on the song select screen like how DDR does lamps. Idk if I'm alone here but, as a glorified checklist, lamps are a great motivator for me to become more consistent at tighter timing windows and push myself to play and practice harder and wackier charts. Additionally, since last ITL gave bonus points for getting better combo types and it's likely that future events will too, having an easy way to view this information would be great since the alternative of viewing a different webpage/program is less than convenient.

**Comment by teejusb** [comment]
Done in: https://github.com/Simply-Love/Simply-Love-SM5/pull/434
