### ISSUE TITLE
Change Font Color of Boss Songs

### ISSUE THREAD

**Issue by Lolrus** [dguzek/Simply-Love-SM5#44]
Some song titles have red fonts in song selection when using the default StepMania theme. It makes it easier to identify ones that are significantly harder than others and for setting goals. Please add this! #

**Comment by dguzek** [comment]
Although I'm not interested in adding this feature at this time, it is easy enough to change on your own copy of the theme.  Use a text editor to modify Metrics.ini and look for these lines:

```ini
# This sets an integer threshold for each song's charts' meters
# if a meter is above this threshold, color the song name differently.
# We don't want this in Simply Love, so set it arbitrarily high.
ExtraColorMeter=999999
```

If, for example, you wanted everything rated 10 and greater to be a different color, you would change the `ExtraColorMeter=10`
