### ISSUE TITLE
Enable 3 panel?

### ISSUE THREAD

**Issue by 1033Forest** [dguzek/Simply-Love-SM5#45]
There is a 3 panel mode in SM5 (dance-threepanel or dance-3panel i believe it was). It is left-down-right (SM 5.0.11) or upleft-down-upright (SM 5.1 or newer).

Solo and 3 panel styles can be enabled or disabled in the options menu.

Will a SM 5.1 version of this theme come soon?

**Comment by dguzek** [comment]
> Will a SM 5.1 version of this theme come soon?

In truth, I haven't thought about it much.  Perhaps the advent of StepMania 5.1 will be an appropriate time for me to retire this theme, which I've worked on for over three years now.  There will likely be outcry, but there is with any change to any aspect of StepMania.

As I understand, @ListenerJubatus is working on a new default theme for StepMania 5.1, which you can check out [here](https://github.com/ListenerJubatus/smtheme-fiftyOne).  Hopefully that will suffice.

Simply Love for SM5 is open-source.  There is nothing stopping any individual from forking this repository, [learning Lua](http://dguzek.github.io/Lua-For-SM5/), and taking up the torch.  Perhaps that individual could be you?  :)

**Comment by 1033Forest** [comment]
I dont really know that much about lua... so I dont really know how to make themes, except just using an existing theme as a base and modifying the graphics

**Comment by dguzek** [comment]
You should learn!  You've demonstrated a keen interest in StepMania, and learning to program and contributing back via code is the best way that I can think of to further that interest.

**Comment by 1033Forest** [comment]
It works on 5.1. But it won't let me select the new noteskins for the new noteskin system. It only lets me choose the old ones, then the new noteskin shows up, which lets me choose between only one noteskin and that's it. But all the old effects work.

**Comment by dguzek** [comment]
> it won't let me select the new noteskins for the new noteskin system. It only lets me choose the old ones, then the new noteskin shows up, which lets me choose between only one noteskin and that's it.

This is the expected behavior for now, because I have not updated the theme to support StepMania 5.1.  I talk about this up above in my [previous comment](https://github.com/dguzek/Simply-Love-SM5/issues/45#issuecomment-225995871).

I do not intend to support 3-panel mode in this theme at this time.
