### ISSUE TITLE
Game freezes periodically during songs. Not sure if this is an issue with my computer or theme. PC: ASUS - ROG Zephyrus 14" WQXGA 120Hz Gaming Laptop - AMD Ryzen 9 - 16GB DDR5 Memory - AMD Radeon RX 6800S - 1TB PCIe 4.0 SSD - Moonlight White/OS: Windows 11

### ISSUE THREAD

**Issue by makoflagkk** [dguzek/Simply-Love-SM5#466]

**Comment by makoflagkk** [comment]
https://user-images.githubusercontent.com/130417801/231258849-d90ca053-3992-4ec4-816f-45dfe6054d99.mp4

**Comment by makoflagkk** [comment]
This issue has happening with two different computers. Strangely enough they are two different types of lags. This happens with all forks of StepMania. And all different versions of the Simply Love theme. I tried switching from d3d to OpenGL but nothing worked.

**Comment by makoflagkk** [comment]
This issue has happening with two different computers. Strangely enough they are two different types of lags. This happens with all forks of StepMania. And all different versions of the Simply Love theme. I tried switching from d3d to OpenGL but nothing worked.

**Comment by teejusb** [comment]
Redirected to: https://github.com/itgmania/itgmania/issues/101
