### ISSUE TITLE
Game freezing during song.

### ISSUE THREAD

**Issue by makoflagkk** [dguzek/Simply-Love-SM5#467]
https://user-images.githubusercontent.com/130417801/231258849-d90ca053-3992-4ec4-816f-45dfe6054d99.mp4

_Originally posted by @makoflagkk in https://github.com/Simply-Love/Simply-Love-SM5/issues/466#issuecomment-1503902423_

**Comment by teejusb** [comment]
Redirected to: https://github.com/itgmania/itgmania/issues/101
