### ISSUE TITLE
Unable to Change to ITG timing windows

### ISSUE THREAD

**Issue by Lolrus** [dguzek/Simply-Love-SM5#49]
There was an option menu to switch the timing windows between ITG and DDR levels. I can't find it anymore. Is it built into competitive mode as per its "ITG Standards?" Do the casual and StomperZ gamemodes use judge and lifebar levels instead?

**Comment by dguzek** [comment]
The theme now manages a subset of Preferences and Metrics for users.  ITG timing windows are now hardcoded into Competitive mode, and StomperZ timing windows are hardcoded into StomperZ mode.  Casual mode uses Competitive timing windows, but eliminates W4 and W5.

You can see which Preferences and Metrics are managed, and what they are set to by peeking into [./Simply Love/Scripts/SL_Init.lua](https://github.com/dguzek/Simply-Love-SM5/blob/4208102ee08d9f0405e751084bb182b693c770e8/Scripts/SL_Init.lua#L99-L290).

Does this answer your question?

**Comment by Lolrus** [comment]
Yes, thank you!

**Comment by dguzek** [comment]
No problem; I'll close this issue now.
