### ISSUE TITLE
No HUD on WaterFall and Zmod fork of Simply Love ITGmania v0.6.0 Windows 11

### ISSUE THREAD

**Issue by makoflagkk** [dguzek/Simply-Love-SM5#498]
![877877789](https://github.com/Simply-Love/Simply-Love-SM5/assets/130417801/65dc4795-0622-4468-8e7f-2b8307183d93)

I've seen other people play on ITGmania and it works fine.  But on my end it the theme does not support the game.  Unsure why that is. Any explanation would be great. Thank you.

**Comment by makoflagkk** [comment]
Fixed. I just had to switch over to ITGmania v0.7.0. I was using a portable version of ITGmania.

**Comment by teejusb** [comment]
Usually blank screens like this means there was a theme error. Zmod generally requires people to up to date with the latest version of ITGm (as does the ITGmania version of Simply Love ).
