### ISSUE TITLE
I have the right version but alot of things are black

### ISSUE THREAD

**Issue by Redpandaboi** [dguzek/Simply-Love-SM5#50]
what to do

**Comment by dguzek** [comment]
When people describe the theme as being "all black" that usually means the theme's directory is nested too deeply.  Can you check that you don't have a `Simply Love` folder inside a `Simply Love` folder or anything similar?

**Comment by Redpandaboi** [comment]
I only see the words, (EX:) When I select something, that is the only thing
I see, when using the first 3 screens, when I select something with words,
that is the only thing I see, and selecting songs will only show the
banner, and the song title, and the background of everything is black.

**Comment by dguzek** [comment]
Yes, that sounds like you've installed the theme incorrectly as I suggested in my initial post.

**Comment by dguzek** [comment]
The folders should be structured [like this](http://www.personal.psu.edu/djg270/sites/sm5/?open=11-4).

**Comment by Redpandaboi** [comment]
ok thanks

**Comment by dguzek** [comment]
Is the issue resolved now?

**Comment by Redpandaboi** [comment]
No idea what to do.

**Comment by dguzek** [comment]
> Can you check that you don't have a Simply Love folder inside a Simply Love folder or anything similar?

**Comment by Redpandaboi** [comment]
When I open the RAR/zip file and then I find a folder called
Simply-Love-SM5-master

**Comment by dguzek** [comment]
What is inside Simply-Love-SM5-Master?

**Comment by Redpandaboi** [comment]
In order there are folders called:
Sounds
Scripts
Languages
Graphics
Fonts
BGAnimations
Then there is:
ThemeInfo.ini
README.md              (I can't open this file)
metrics.ini

**Comment by dguzek** [comment]
Okay, then the top-level folder (Simply-Love-SM5-Master) is the one you
want to put in the Themes folder.

**Comment by Redpandaboi** [comment]
OK

**Comment by dguzek** [comment]
Is the issue resolved now?

**Comment by Redpandaboi** [comment]
Yes! Thank so much!
