### ISSUE TITLE
Theme is completely broken in Stepmania 5.1

### ISSUE THREAD

**Issue by MrThatKid** [dguzek/Simply-Love-SM5#51]
If you were to try to use this theme in 5.1, everything breaks from the very start. This is because ThemePrefs was removed in 5.1 in favor of the "lua_config" system.
Here's the details, if you want them.
Details of the removal here: [ThemePrefs_removed.md](https://github.com/stepmania/stepmania/blob/5_1_0/Docs/Themerdocs/5.1_incompatibilities/ThemePrefs_removed.md)
Details of lua_config: [lua_config_system.md](https://github.com/stepmania/stepmania/blob/5_1_0/Docs/Themerdocs/lua_config_system.md)
If you remove all encountered instances of ThemePrefs (and use hardcoded values) to get the theme usable there (don't do this as the fix), the evaluation screen statistics are also broken.

Where you'd usually see "GREAT ###", there's now "GREAT 000000000" with the zeros overlapping the text. This applies to all judgment statistics and holds/mines/hands/rolls (although the /### part seems to work)
Also, NewField exists, so the normal noteskin option doesn't work anymore.
If you do wish to fix this, you may want to make a separate branch, as Stepmania 5.0, doesn't seem to have the lua_config system.

**Comment by dguzek** [comment]
Thanks for filing the issue.

I was aware that the theme completely breaks in SM5.1; I have no intentions
of making it work in SM5.1 at this time.

I encourage those who used Simply Love in the past to look into other
themes.

**Comment by dguzek** [comment]
I (could be wrong) but I anticipate that the only themes that don't break
in SM5.1 are default and Consensual. Thus, I suppose I encourage you to
look into those themes.

**Comment by dguzek** [comment]
For better or worse, I've created a new branch for this theme that targets SM5.1: 

<https://github.com/dguzek/Simply-Love-SM5/tree/5_1_0>

**Comment by kyzentun** [comment]
I have my own branch that migrates prefs from ThemePrefs and your lua file to the lua config system, among other things.

https://github.com/kyzentun/Simply-Love-SM5/tree/5_1_migration

If you want to load a lua config file safely on 5.0, you can copy the load_conf_file function from Consensual/Scripts/00 settings_system.lua
On 5.1, you can use ```lua.load_config_lua(file_path)``` to load the file.
Both take a file path, and return the lua table with the config data.
