### ISSUE TITLE
(GrooveStats integration) leaderboard doesn't show after passing a song on StepMania 5.1.0-b2

### ISSUE THREAD

**Issue by Vanishing-Point** [dguzek/Simply-Love-SM5#528]
Using GrooveStats Launcher v1.6.0, StepMania v5.1.0-b2 and Simply Love v5.4.0.

In the results screen after passing a ranked song in ITL Online 2024, submitting finishes successfully (can be seen in online leaderboards) and the screen gets darkened. However, the leaderboard window doesn't show up. Furthermore, the submission status incorrectly says "Submitting ...".
![2024-03-12_163842](https://github.com/Simply-Love/Simply-Love-SM5/assets/8634851/34f12e83-740e-4b40-bc92-5de2b9385600)

The leaderboard window works as normal when accessed from the song selection wheel screen.

**Comment by Horsey-** [comment]
Same exact symptoms here

**Comment by concubidated** [comment]
`Error playing command:...imations/ScreenEvaluation common/Shared/EventOverlay.lua:379: attempt to perform arithmetic on a nil value (local 'previousPoints')
`


```
diff --git a/BGAnimations/ScreenEvaluation common/Shared/EventOverlay.lua b/BGAnimations/ScreenEvaluation common/Shared/EventOverlay.lua
index 278e8f6f..8d4aaaf3 100644
--- a/BGAnimations/ScreenEvaluation common/Shared/EventOverlay.lua      
+++ b/BGAnimations/ScreenEvaluation common/Shared/EventOverlay.lua      
@@ -375,7 +375,10 @@ local GetItlPaneFunctions = function(eventAf, itlData, player)
        end
 
        local currentPoints = GetITLPointsForSong(maxPoints, score)
-       local previousPoints = itlData["topScorePoints"]
+       local previousPoints = 0
+       if itlData['topScorePoints'] ~= nil then
+                previousPoints = itlData["topScorePoints"]
+       end
        local pointDelta = currentPoints - previousPoints
 
        local currentRankingPointTotal = itlData["currentRankingPointTotal"]
```

**Comment by concubidated** [comment]
Was a bug in GSlauncher, need to update

https://github.com/GrooveStats/gslauncher/commit/e2f82cead41216193ab967039301fdcbc6102271

**Comment by Vanishing-Point** [comment]
Okay, it took me a while but I have tested it out. Indeed, the patch @concubidated linked fixes the issue.
![2024-05-13_135920](https://github.com/Simply-Love/Simply-Love-SM5/assets/8634851/149ab3e1-9e16-4683-b9a5-5ef7a5c01904)
It still says "Submitting ...", but maybe this has to do with me also modifying the launcher to send scores through BoogieStats, I dunno. Either way, the main issue is fixed.

However, the code fix is not part of the final release of the GrooveStats Launcher (1.6.0), so unfortunately anyone else with this issue has to apply the patch themselves and follow the guide for building the GrooveStats Launcher manually: https://github.com/GrooveStats/gslauncher/blob/main/doc/building.md

But that's okay, since I strongly suspect most of the people participating in GrooveStats-hosted online events have already made the switch to ITGMania, and the rest of us will be forced to do that anyway in the near future. Personally, I only haven't done that yet because I'm too obstinate. And the early decent/way off correction mechanism will be a huge boon for these types of events.

**Comment by Horsey-** [comment]
Yeah,I also have the visual bug where it’s stuck saying submitted.
