### ISSUE TITLE
ScreenGameplay::TimingWindowScale program error when Judge != 4

### ISSUE THREAD

**Issue by LumiStar2000** [dguzek/Simply-Love-SM5#530]
Reproduction steps:
on ITGmania 0.8.0 and SL 5.4.0 for ITGmania, select any judgement other than Judge 4 (TimingWindowScale != 1), and attempt to play a song.  Error is thrown 100% of the time.

I believe the bug is related to the options display at song start. 
The song appears to play fine when "Ignore" is selected, and "xx% Judgement Windows" displays on the results screen, all as intended, but the options display just ends with a ",".
![image](https://github.com/Simply-Love/Simply-Love-SM5/assets/23439491/38cd0507-356a-43de-8559-1f92247cafe1)
![image](https://github.com/Simply-Love/Simply-Love-SM5/assets/23439491/b11431e0-3700-4e3b-b303-633a0d33860b)

**Comment by SugoiFactory** [comment]
The language string is missing for ScreenGameplay, I've made an MR to address this:
https://github.com/Simply-Love/Simply-Love-SM5/pull/531
