### ISSUE TITLE
Measure Lines Drawn when Language is set to Japanese

### ISSUE THREAD

**Issue by nabulator** [dguzek/Simply-Love-SM5#538]
From ITGmania 0.8.0 an ArchLinux. Reproduced on Windows 10. 

Irrespective of options set during a song, measure lines seem to be drawn regardless in game mode. 
Changing the options explicitly to draw `eights` or `quarter` does not seem to affect the number of lines drawn.

**Comment by teejusb** [comment]
This is already fixed in beta via: https://github.com/Simply-Love/Simply-Love-SM5/commit/43ea43fbdb9c858de75cc3ec93d58ac6c70dea99
