### ISSUE TITLE
.sm: chart matching in SL-ChartParser.lua fails on empty NOTES props

### ISSUE THREAD

**Issue by florczakraf** [dguzek/Simply-Love-SM5#555]
```
if #parts >= 7 then
```
doesn't pass for charts with empty properties, for example when a step-artist field is empty (there's no whitespace -- for example a line break between the colons):
```
(...)
#NOTES:dance-single::Medium:4:0.000,0.000,0.000,0.000,0.000:
0000
0000
0000
0000
,
(...)
```
I think that the "radar" field can also be empty without any consequences.

This is directly related to the following regex:
```
for part in normalizedNoteData:gmatch("[^:]+") do
    parts[#parts+1] = part
end
```

As a result, the hash calculation for a chart is not performed, so there's no online ranking available. "Tech" breakdown and density graph are also empty: 
![image](https://github.com/Simply-Love/Simply-Love-SM5/assets/9034451/e67520df-8823-4fd5-91c5-abc43c68b4d1)

This is not a completely unrealistic case, I've just grepped my library and found 396 affected charts.

**Comment by teejusb** [comment]
Seems like an easy fix. The `+` should be a `*` to include empty strings. Will get it into the next release.

**Comment by florczakraf** [comment]
I don't think it works. I applied it locally and tested on ITG 2:

before:

![image](https://github.com/Simply-Love/Simply-Love-SM5/assets/9034451/fc7e4b64-70c3-4b50-8443-b464c1f9cc09)


after:

![image](https://github.com/Simply-Love/Simply-Love-SM5/assets/9034451/024619ea-abe6-45aa-b83b-6d37f746e97f)

It seems to perform a greedy match so that everything is now put in the first `part`

**Comment by teejusb** [comment]
Oh hmm weird, I tested it with this:
https://ideone.com/Z04as9

but could be a different lua version lemme look into it

**Comment by teejusb** [comment]
https://github.com/Simply-Love/Simply-Love-SM5/commit/e8671ff81f3efa975111ee7b0b0adc0de41c5421
was my commit.

**Comment by florczakraf** [comment]
> Oh hmm weird, I tested it with this: https://ideone.com/Z04as9
> 
> but could be a different lua version lemme look into it

Indeed:

lua5.1:
```
florczak-> lua5.1 test_parser.lua 
before
1 #NOTES
2 dance-single
3 Medium
4 4
5 0.000,0.000,0.000,0.000,0.000
6 
0000
0000
0000
0000
after
1 #NOTES
2 
3 dance-single
4 
5 
6 Medium
7 
8 4
9 
10 0.000,0.000,0.000,0.000,0.000
11 
12 
0000
0000
0000
0000
13 
```

lua5.3:
```
florczak-> lua5.3 test_parser.lua 
before
1 #NOTES
2 dance-single
3 Medium
4 4
5 0.000,0.000,0.000,0.000,0.000
6 
0000
0000
0000
0000
after
1 #NOTES
2 dance-single
3 
4 Medium
5 4
6 0.000,0.000,0.000,0.000,0.000
7 
0000
0000
0000
0000
```

**Comment by teejusb** [comment]
Committed this:
https://github.com/Simply-Love/Simply-Love-SM5/commit/5e8b9e1f88e25d090f671d2e2b829f3d678b7918

I tested it locally with the above test and got:

```
before
1 #NOTES
2 dance-single
3 Medium
4 4
5 0.000,0.000,0.000,0.000,0.000
6 
0000
0000
0000
0000

after
1 #NOTES
2 dance-single
3 
4 Medium
5 4
6 0.000,0.000,0.000,0.000,0.000
7 
0000
0000
0000
0000
```

So seems good from the interpreter side, but I didn't check in game.

**Comment by florczakraf** [comment]
Looks like it could work but there's a typo. I commented directly on the diff

**Comment by teejusb** [comment]
Thanks for the catch! Updated itgmania-beta: https://github.com/Simply-Love/Simply-Love-SM5/commit/7f2a571446e665d068ed92c0ed84047f7dc4d268
