### ISSUE TITLE
Why is there no place to change your offset? (5.4)

### ISSUE THREAD

**Issue by ghost** [dguzek/Simply-Love-SM5#558]
I've have a very big event that makes HEAVY use of Simply Love 5.4 and I need to get the offset excatly right. Problem is, I can't change it. If I don't get it right, things are going to get really difficult for me to manage. And I know that SL adds its own offset by default, so what happens and what should I do?

**Comment by teejusb** [comment]
??

It's literally in the operator menu under Graphics/Sound Options. Also SL doesn't add an offset by default.

<img width="1665" alt="image" src="https://github.com/Simply-Love/Simply-Love-SM5/assets/5017202/e18505f6-0d20-4dac-9c0a-dd91748e4c00">

**Comment by ghost** [comment]
I meant the interactive stepping field where you use your gameplay to autosync:

![Screenshot 2024-06-25 181116](https://github.com/Simply-Love/Simply-Love-SM5/assets/166316583/7524523c-98c1-4d40-9722-e19ea9de791a)


At least it doesn't mess with your offset when you switch in and out.

**Comment by teejusb** [comment]
Press F6 twice during gameplay

**Comment by ghost** [comment]
wait that works here too??

**Comment by KisanoWasTaken** [comment]
Oh, that works here too? Nice.

Well have a nice day, mate.
