### ISSUE TITLE
Note bursts use wrong colors in ECFA

### ISSUE THREAD

**Issue by Paljero** [dguzek/Simply-Love-SM5#58]
FA uses blue, FA- uses yellow, EX uses green, GR uses blue and so on. Need to add a white note burst, or just use the fantastic one for both of them.

**Comment by dguzek** [comment]
Hi, thank for submitting this issue.

The bursts you are describing are specific to the NoteSkin you are using.  It is not something the theme has any control over in SM5.0.12.
