### ISSUE TITLE
Result Screen BG Music vs. Score Vocalizer

### ISSUE THREAD

**Issue by RodentVienna** [dguzek/Simply-Love-SM5#59]
The Score Vocalizers cannot be understood properly, as the BG Music is running. An approach to resolve would be to allow the BG Music being turned off. This could be achieved by adding one entry to the vocalize modifier, which then would read like "Off | BG Music only | Joy | Jayce | Matt" (etc).

**Comment by dguzek** [comment]
ScreenEvaluation doesn't have any background music.  I don't know what you're talking about.

**Comment by RodentVienna** [comment]
my apologies, turned out, this was a personal addition of mute, which got distributed with his SSD. nvm.
