### ISSUE TITLE
"Personal Best" in Results screen (+ Machine Best)

### ISSUE THREAD

**Issue by RodentVienna** [dguzek/Simply-Love-SM5#60]
Upon beating his own best score on a song, on top left (P1) or top right (P2) a text is shown "Personal Best". This text is "barely" visible, in context to other contrastfully stylized elements. could this be made bigger and more prominent to see? (blinking is all cool though).

Also, can a "Machine Best" indicator added as well?

**Comment by dguzek** [comment]
[Code already exists](https://github.com/dguzek/Simply-Love-SM5/blob/master/BGAnimations/ScreenEvaluation%20common/PerPlayer/RecordTexts.lua#L32-L37) to display Machine Records on ScreenEvaluation.  It works well enough; I have no intention of changing it.
