### ISSUE TITLE
Game Modes "universalized"

### ISSUE THREAD

**Issue by RodentVienna** [dguzek/Simply-Love-SM5#61]
a lot of effot was put into game modes for casual, competitive, ecfa and stomperz. This i believe is a super-awesome concept, but it is limiting in certain ways, as you have to choose for a game mode in order to have a certain feature. 

The cool features are, that it is possible to add judgment windows (ridiculous timing concept), and to move around certain elements from gameplay screen, such as combo, judgment, (maybe) targets.

1) would it be possible to give some freedom in placing these elements for each player within the modifier menu?
- combo y-axis; judgment y-axis
- ridiculous timing on-off modifier (comprable to decent/way-off off).

2a) would it be possible to either create a blueprint package of what consist of a "game mode", in order for users to create (and share) their oen game modes?

or

2b) would it be possible a "custom" game mode is created, which parameters can be defined in op menu, or a settings-file?

**Comment by dguzek** [comment]
I am not interested in extending the functionality of GameModes at this time.  Given the flexibility you are requesting, it sounds like you want kyzentun's Consensual theme.
