### ISSUE TITLE
Going into Options menu does not properly restore Theme Color preference

### ISSUE THREAD

**Issue by FishamanP** [dguzek/Simply-Love-SM5#64]
Pretty easy to replicate on my end. Boot up, go into Options by either the menu option or the Service button, and go back out. The text changes (in my case) from blue to red, reliably. Properly resets to blue after restarting SM5.

Issue happening on commit 413b7f2, plus some way back but haven't bisected

**Comment by dguzek** [comment]
To clarify: "the text" changes color when you leave ScreenOptionsService and return to ScreenTitleMenu/ScreenTitleJoin?

Can you be more specific about what is happening vs what you think should happen?  As it stands, I am fairly confused by your description.

**Comment by FishamanP** [comment]
[http://imgur.com/a/1EXGF](http://imgur.com/a/1EXGF)
Getting direct screenshots off my setup is a pain, so I used a camera and did my best to capture accurate colors.

In ThemePrefs.ini, SimplyLoveColor=6, and I didn't find that pref in any other file so idk

**Comment by dguzek** [comment]
I see now.

I'm unable to recreate this issue and I've never heard of it happening before, but I'll try to help you figure out what is going on.  Let's start with: what version of StepMania 5 are you using?

**Comment by FishamanP** [comment]
Unknown commit of 5.1-new compiled with XP Platform Toolset, on XP Embedded. DirectX renderer.

Installed to custom directory on D: and portable.ini exists.

ScreenSelectColor is disabled.

**Comment by dguzek** [comment]
It seems to be related to ScreenSelectColor being disabled.

This will be very low on my priority list (I may never get around to fixing it) so pull requests are welcome.

**Comment by dguzek** [comment]
Never mind.  This should be resolved as f37dca42fac1f66761b26a4c89dd8a7faf3b8f18.  If not, let me know and I'll reopen this issue.

**Comment by FishamanP** [comment]
Issue confirmed fixed. Thanks for the quick work!
