### ISSUE TITLE
"File doesn't exist"

### ISSUE THREAD

**Issue by PCBoyGames** [dguzek/Simply-Love-SM5#65]
SM5 crashed.
Reason: "/Themes/Simply-Love-SM5-master/BGAnimations/ScreenGameplay underlay/default.lua:29: references a file "/Themes/Simply-Love-SM5-master/BGAnimations/ScreenGameplay underlay/PerPlayer/StepStatistics/default.lua" which doesn't exist"

EDIT: Continuing causes everything but the playfields, combos, and judgment to disappear.

**Comment by dguzek** [comment]
Does the file mentioned in your crash log exist in your theme?
