### ISSUE TITLE
ingame progress graph broken by Forever Young (Groovestats)

### ISSUE THREAD

**Issue by Horsey-** [dguzek/Simply-Love-SM5#68]
![2017-10-15 22_44_44-simply love](https://user-images.githubusercontent.com/5679966/31704573-d814d528-b396-11e7-9b19-f5d0e18be51b.png)

[Initial D - Forever Young.zip](https://github.com/dguzek/Simply-Love-SM5/files/1393671/Initial.D.-.Forever.Young.zip)

**Comment by dguzek** [comment]
Simply Love's chart parsing script is imperfect and will be for the foreseeable future.  You're aware of this as [you commented on](https://github.com/dguzek/Simply-Love-SM5/commit/319f622016b0087a90ce5409e225ce46319620c6#commitcomment-21910500) the last commit that touched that functionality.

There are infinitely many edge cases that will break the pattern matching it uses and I don't have time to properly convert the engine's MSD parser to Lua and integrate that into the measure counter and NPS histogram right now.  It's not throwing any Lua errors so it's degrading gracefully, at least.

**Comment by dguzek** [comment]
Oh, I see.  Forever Young capitalizes the file extension like `.SM`, breaking the pattern matching that locates the ssc/sm file itself. That's kind of... tangential to the chart-parsing code, and an easy enough fix.

This should be resolved by f6bbabd677aa9a71711757916bc8d27bc0f8279c.
