### ISSUE TITLE
"Random" breaks the game

### ISSUE THREAD

**Issue by ianklatzco** [dguzek/Simply-Love-SM5#70]
If you hit random, the songwheel spins (roulette's normal behavior). If you hit green while you're on a song inside the randomly-opened pack, you start the song.

If you hit green while over a songpack, the game locks up.

![gif](https://user-images.githubusercontent.com/1487413/32705070-65531d08-c7d5-11e7-91a9-a957fab6f176.gif)

**Comment by dguzek** [comment]
This is an issue with StepMania, not Simply Love, as we discussed.

I can remove Random from the MusicWheel if that works?

**Comment by ianklatzco** [comment]
I think that's the best solution.

**Comment by dguzek** [comment]
Alternatively, here are two patches for SM5  that mostly fix this issue.  You should be able to apply these via `git apply`.

```
From a8d0cb851610e75d50f675933ddfe96377366232 Mon Sep 17 00:00:00 2001
From: Dan Guzek <dguzek@gmail.com>
Date: Sat, 28 Nov 2015 20:47:18 -0500
Subject: [PATCH 1/2] have Random only pick from currently open pack

---
 src/MusicWheel.cpp | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)

diff --git a/src/MusicWheel.cpp b/src/MusicWheel.cpp
index 745bd36..90e919c 100644
--- a/src/MusicWheel.cpp
+++ b/src/MusicWheel.cpp
@@ -1345,13 +1345,13 @@ void MusicWheel::StartRandom()
 	{
 		GAMESTATE->m_SortOrder.Set( GAMESTATE->m_PreferredSortOrder );
 	}
-	SetOpenSection( "" );
-
-	m_Moving = -1;
-	m_TimeBeforeMovingBegins = 0;
-	m_SpinSpeed = 1.0f/ROULETTE_SWITCH_SECONDS;
-	m_SpinSpeed *= 20.0f; /* faster! */
-	m_WheelState = STATE_RANDOM_SPINNING;
+//	SetOpenSection( "" );
+//
+//	m_Moving = -1;
+//	m_TimeBeforeMovingBegins = 0;
+//	m_SpinSpeed = 1.0f/ROULETTE_SWITCH_SECONDS;
+//	m_SpinSpeed *= 20.0f; /* faster! */
+//	m_WheelState = STATE_RANDOM_SPINNING;
 
 	SelectSong( GetPreferredSelectionForRandomOrPortal() );
 
-- 
2.6.3
```

```
From 31d6638d1d7983e2cd756efcbfbc361ba334cf34 Mon Sep 17 00:00:00 2001
From: Dan Guzek <dguzek@gmail.com>
Date: Sat, 28 Nov 2015 21:08:32 -0500
Subject: [PATCH 2/2] update engine's sense of CurrentSong

---
 src/MusicWheel.cpp | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/src/MusicWheel.cpp b/src/MusicWheel.cpp
index 90e919c..209486d 100644
--- a/src/MusicWheel.cpp
+++ b/src/MusicWheel.cpp
@@ -1353,6 +1353,8 @@ void MusicWheel::StartRandom()
 //	m_SpinSpeed *= 20.0f; /* faster! */
 //	m_WheelState = STATE_RANDOM_SPINNING;
 
+	SCREENMAN->PostMessageToTopScreen( SM_SongChanged, 0 );
+	
 	SelectSong( GetPreferredSelectionForRandomOrPortal() );
 
 	RebuildWheelItems();
-- 
2.6.3
```

**Comment by dguzek** [comment]
It looks like this pull request, if merged, would also resolve this issue. https://github.com/stepmania/stepmania/pull/1612

**Comment by Kauhsa** [comment]
@dguzek you sure? Is so, that's great, but I don't follow how it's related :smile: Can't test right now, but my PR only changes what `GetPreferredSelectionForRandomOrPortal()` outputs - from what I can see on the code, that is relevant only when selecting the initial random pack that is opened and nothing afterwards. Is there something I'm not seeing here?

**Comment by dguzek** [comment]
I misunderstood what your SM5 pull request did.  Sorry about this.

**Comment by Kauhsa** [comment]
It's okay! Random is probably worth fixing as well. The core of the issue is that the song packs are visible in SongWheel after Random is launched, right? Those can be probably filtered out (well, on Stepmania rather than here, but anyways) if the current random behaviour is otherwise desired.

**Comment by Kauhsa** [comment]
Although - while it's been too long for me to remember how it used to work, this whole thing started when people in our local community started longing after "ITG/OpenITG random" - which I found is called "Portal" in the codebase. Other than portal doesn't... really work that well in current SM5 IMHO (thus my PR), it would probably be worth adding to this theme if old ITG crowd is the main userbase? :) I've done it myself here: https://github.com/Kauhsa/Simply-Love-SM5/commit/328f5206e0ac1e6560a4af7b7e648de351a587ef

**Comment by Flameshadowxeroshin** [comment]
CHANCE is what SM5 calls RANDOM i believe.

**Comment by dguzek** [comment]
@Flameshadowxeroshin – The intent of those patches was to get the MusicWheel's RANDOM behavior to be more in line with how ITG behaved.  That is:

1. Don't scroll the MusicWheel like Roulette
2. Ensure that the randomly-chosen song was within the currently-open song pack if one was open, or from anywhere, if no song pack is currently open.

The patches mentioned above _usually_ seem to resolve those two issues, but not always (the worst kind of bug!).  If a particular song pack is currently open/expanded in the MusicWheel, these patches will usually pick a song randomly from that pack, but occasionally you'll end up in some other pack.

I haven't tested to see if this changes once @Kauhsa's pull request [1612](https://github.com/stepmania/stepmania/pull/1612) to StepMania is applied.
