### ISSUE TITLE
Elements on ScreenPlayerOptions are hidden by arrow

### ISSUE THREAD

**Issue by DinsFire64** [dguzek/Simply-Love-SM5#74]
Dan,

I recently pulled your last commit onto my cabinet (running 5_1-new branch) and the player options screen started acting weird.

I don't have much time to diagnose it with the holidays that I need to prepare for, so I thought I would throw this out there.

A lot of the options are hidden by the down arrow with my current preferences. Resetting my Stepmania preferences to default clears this issue. I have attached the diff in preferences and a screenshot of the issue.

[prefDiff.txt](https://github.com/dguzek/Simply-Love-SM5/files/1494633/prefDiff.txt)

![2017-11-21_222213](https://user-images.githubusercontent.com/5580979/33110340-d2d7d222-cf0c-11e7-8b82-8efdb3fcf629.jpg)

**Comment by dguzek** [comment]
Yes, this is the expected OptionRow behavior when ThreeKeyNavigation is
enabled. Is it not desirable?

**Comment by DinsFire64** [comment]
Hey Dan, thanks for the quick reply.

So I was looking more at my diff and changing the preference `ArcadeOptionsNavigation` to `0` is the desired functionality for me. This allows me to see my current preferences at a glance as they are not hidden by the arrow. For example I cannot see what my current mini mod is or the current music rate.

Looking at the commit though, how did your change implement this functionality?

**Comment by DinsFire64** [comment]
So forgive me as my knowledge of the stepmania codebase is very limited.

I was looking more into what all ThreeKeyNavigation triggers and all it seems to do is toggle `NavigationMode` from `"normal"` to `"toggle"` through `OptionsNavigationMode()`.

This was unexpected for me as I am used to seeing the normal screen. I would suggest overriding the `NavigationMode` in metrics.ini `[ScreenOptions]` to force `"normal"`.

I found the `"toggle"` `NavigationMode` to be cumbersome as I had to hit green to get into the setting, see if it was the right option, change it if it wasn't, then accepting it by hitting green. Compare that to glancing at the option, changing it, then accepting it by hitting green.

That would satisfy myself, what do you think?

**Comment by dguzek** [comment]
Hmm.  So, you would recommend setting `NavigationMode="toggle"` under `[ScreenOptions]` in Metrics.ini?  That would impact all screens that inherit from ScreenOptions.

Can you test that out and let me know if it work for you?   I don't have/use a DDR cabinet, myself, and will basically do whatever you think is best here.

**Comment by DinsFire64** [comment]
Dan,

Thanks for the response. I was actually saying force to "normal" for all option rows as a default. That would prevent this arrow from appearing on all inherited screens yes. 

I was testing it a bit last night and didn't see any issue, but I didn't have much time for a full check out. 

I'll have my laptop with me this weekend so I can check it out more.

**Comment by DinsFire64** [comment]
Yeah Dan, going through the menus forcing "normal" is desired for me. I can make a pull request if you would like.

**Comment by dguzek** [comment]
Can you still navigate through all the menus and submenus within the operator menu?  How about edit mode?  Can you still create and manage local profiles?

I'm hesitant to change `[ScreenOptions]` because _so_ many things inherit from it...

**Comment by DinsFire64** [comment]
If you look at like _fallback theme that would inherit it, the only time that `NavigationMode` changes in `[ScreenOptions]` is when `ThreeKeyNavigation` is modified, unless I am reading this wrong.

https://github.com/stepmania/stepmania/blob/78e8c2a1e9148ec3df4967325b980274fcd9dcca/Themes/_fallback/metrics.ini#L2216

https://github.com/stepmania/stepmania/blob/4df85929cc2e41ef8c24bddea17d90fe44fb2807/Themes/_fallback/Scripts/02%20Other.lua#L136

**Comment by dguzek** [comment]
Thanks.

Let me know if f591ceb7afc79212c2684eeb57ff84eba77c03d1 resolves this issue.

**Comment by DinsFire64** [comment]
Dan,

This does fix my issue thank you; however, I had never used the MachineProfile management screen before as I use USB sticks on my cabinet. It was broken with only three keys for a while now oddly enough.

Pulling the last stable release (4.3) and trying the MachineProfile screen, there is no way to operate it without a MenuDown or MenuUp key. The selected row is the only one that one can interact with. Holding MenuLeft and MenuRight then pressing green doesn't work to go up with the submenu and there is no arrow to go down.

Even though I don't use it, adding an up/down arrow at the beginning of that row would allow someone to navigate around that list. Does OptionRow even support an up arrow? What do you think should happen?

Below is a screenshot of stable 4.3 with 5_1-new branch of Stepmania with ThreeKeyNavigation turned on or off, it is the same.

![screenshot from 2017-11-24 10-59-19](https://user-images.githubusercontent.com/5580979/33219538-5987bf74-d108-11e7-9284-2bd88bd77a01.png)

**Comment by dguzek** [comment]
Thanks for pointing this out.   It's definitely a usability issue and users could certainly get stuck on this screen without a keyboard.

> It was broken with only three keys for a while now oddly enough.

It's actually never functioned with only three keys, I just tried not to think about it because I didn't know how to fix it.

**Comment by DinsFire64** [comment]
Yeah I'm with you there, I see it as a problem, but I don't have a good suggestion either.

The consolation is that most people running SM5 on their cabinets, public or private, tend to have keyboards attached somewhere. At least I have a mini wireless keyboard for small terminal stuff. 

Should I close this and open a new issue? I consider this a low priority issue for me, but someone else may disagree. 

Thanks for all the communication man. My offer for beer still stands if we ever cross paths.

**Comment by dguzek** [comment]
I think this particular issue has been resolved and can be closed.  If you want to open a new GitHub issue regarding ScreenOptionsManageProfiles, you may do so, I just may never get around to fixing it...
