### ISSUE TITLE
White Space Visible under 5.0.12. Fixed on 5.1

### ISSUE THREAD

**Issue by dougshell** [dguzek/Simply-Love-SM5#82]
Please see attached screenshots. 

This is with the newest version pulled from github. 
Unsure how to bisect with github revisions or else i would try to point to which change caused the issue. Admittedly, I am a noob so this may be on my end.

First screenshot is from 5.1 20171129 build. Second is from 5.0.12 executable.
![2018-01-07_205246](https://user-images.githubusercontent.com/4993555/34656819-31229d3a-f3ed-11e7-91d2-78bfdd4d2438.jpg)
![2018-01-07_205036](https://user-images.githubusercontent.com/4993555/34656829-416aa44e-f3ed-11e7-9fc0-e2e40efb568d.jpg)
![2018-01-06_215746](https://user-images.githubusercontent.com/4993555/34656830-448fd48c-f3ed-11e7-821a-4cb702bd3725.jpg)

**Comment by dguzek** [comment]
It looks like you have ShowMasks turned on in your SM5.0.12 executable.  This is a StepMania feature and unrelated to theme code.

You can toggle this setting by holding <kbd>F3</kbd> and tapping <kbd>F6</kbd> to activate the Theming Menu, then holding <kbd>F3</kbd> and tapping <kbd>1</kbd> to toggle the setting on and off.

Hope this helps.
