### ISSUE TITLE
Displaying difficulty levels on the songwheel

### ISSUE THREAD

**Issue by lukeoftheaura** [dguzek/Simply-Love-SM5#86]
Dies this theme have an option to display song difficulty levels on the songwheel the same way it can display your grades for each song?

**Comment by dguzek** [comment]
What do you mean by *difficulty level*?  Are you referring to the numerical meter (the 1-20 scale in DDR, or the 1-13 scale in the original ITG) of the current chart or the Difficulty of the current chart (Beginner, Easy, Medium, Hard, Expert)?

**Comment by lukeoftheaura** [comment]
I mean the numerical meter, for whatever difficulty level is currently selected (for example if I selected the expert difficulty on the previous song I player, it would show grades for expert difficulty)

**Comment by dguzek** [comment]
>for example if I selected the expert difficulty on the previous song I player, it would show grades for expert difficulty

The ability to show grades in the MusicWheel was recently added and is included in the [v4.5 release](https://github.com/dguzek/Simply-Love-SM5/releases/tag/4.5).  You can see you letter grade (quad star, triple star, S+, C-, etc.) for a given difficulty for each chart in its associated MusicWheelItem.

As I mention in the release notes for v4.5:
>This feature is disabled by default, but you can enable it under Simply Love Options in your operator menu. It is additionally worth noting that grades are only displayed when a profile (either local or USB stick) is in use. Machine high scores are not displayed because that wouldn't make sense in the context of a public arcade machine.

Does this answer your question?

**Comment by lukeoftheaura** [comment]
no, by grades I mean like the difficulty numbers, like a 9 or 13 or whatever. I don't know the correct terminology for a lot of things.

**Comment by dguzek** [comment]
Ah, okay, I understand now.  You're asking about a chart's _difficulty meter_.  There is no option for displaying meters in MusicWheelItems.  

The currently selected chart's meter is displayed fairly prominently in the large colored block at the bottom of the screen.  I'm not sure it makes sense to duplicate this information.  Do you think it should appear twice on the screen?

**Comment by dougshell** [comment]
The only benefit to this feature addition would be for attempting to
complete songs of a certain difficulty thought a pack or song set. For the
OP if the feature request, you may want to look into sorting by difficulty.
With this feature, you could for instance, attempt to pass all 8 step songs
you have, then move on to 9 step, etc...

**Comment by dguzek** [comment]
Sorting the MusicWheel is quite a different matter than displaying the difficulty meter in MusicWheelItems.

I don't believe what you're describing (sorting by difficulty meter) is currently possible with the engine's MusicWheel, which Simply Love uses.  Available SortOrders with descriptions of each is available [here in the StepMania source code](https://github.com/stepmania/stepmania/blob/5_1-new/src/GameConstantsAndTypes.h#L159-L186).

I'm going to close this issue now.

**Comment by dguzek** [comment]
Oops, I didn't notice at first that @dougshell commented instead of @lukeoftheaura.  What I wrote still applies, however.
