### ISSUE TITLE
seeking opinion - Target position and notefield behavior using "Reverse"

### ISSUE THREAD

**Issue by RodentVienna** [dguzek/Simply-Love-SM5#87]
Hello,

I am kindly asking for your strong opinions - please see this:
[https://i.imgur.com/DerAlF9.jpg](url)

you are looking at sl 4.5 in sm 5.0.12 on windows 10.
the screen shows p1 in regular scroll dir. p2 is in reverse scroll dir.

My observations:
- in all 4-panel dance games i have observed, ddr, itg and even the new ddr A have their target receptors positioned as far to the screen border as possible, but without interfering UI elements.

In DDR A, even some UI Elements get "reversed" from bottom to top as well, when Reverse is enabled.

in simply love however, i am starting to think that Reverse is claiming unintended space from the total playfield distance. please see the corresponding numbers in the image:

Regular Scroll:
(1) in regular scroll, the receptors almost touc the ui element (difficulty/score)
(3) the resulting visible playfield is from receptor to bottom screen border

Reverse Scroll:
(2) in reverse scroll, the receptors are far more distant from the next-possible ui-element (screen border)
(4) the playfield is shorter
(5) the arrows overlap the UI elements "stealing playfield visibility" from the totsal scroll distance.
(tho, on p1 side, if you miss an arrow, the arrows also overlap; just not captured on the screenshot.)

1) is the z-index as intended? (arrows overlapping UI)
2) what is your thinking on the receptor position in reverse?

Thanks in advance - your opinion will help me for this issue, and a new feature i am working on, which is related to receptor position.

/Alex

**Comment by RodentVienna** [comment]
update: DDR A has the arrows scroll under UI element upon a miss. i tend to think this is the natural behaviour, but am not sure.

**Comment by dguzek** [comment]
>in all 4-panel dance games i have observed, ddr, itg and even the new ddr A have their target receptors positioned as far to the screen border as possible

I can't speak for arcade ITG, but OpenITG's fallback theme [defines the y-position of the ReceptorArrows here](https://github.com/openitg/openitg/blob/master/assets/d4/Themes/fallback/metrics.ini#L2776), specifically to `ReceptorArrowsYReverse=144`

Simply Love for ITG/OpenITG [adds 1px to this value](https://github.com/concubidated/simply-love-openitg/blob/master/metrics.ini#L2420) by defining as `ReceptorArrowsYReverse=145`.

Simply Love for SM5 uses the same values as Simply Love for ITG/OpenITG, and they are [defined here](https://github.com/dguzek/Simply-Love-SM5/blob/master/metrics.ini#L1834) like `ReceptorArrowsYReverse=SL.Global.GameMode=="StomperZ" and 170 or 145`.

So, the y-position of the ReceptorArrows when *Reverse* is enabled is (effectively) the same across   

* OpenITG's fallback theme
* Simply Love for ITG
* Simply Love for SM5.  

Furthermore, Simply Love for SM5 targets the post-ITG community as its primary userbase, and I wouldn't want to disrupt the positioning of a core ITG gameplay element that has been stable for thirteen years.  Simply Love is decidedly not DDR.

Yes, the z-index you've observed is intentional.

**Comment by RodentVienna** [comment]
thanks for clarifying the z-index question.

for reverse:
I just checked SL for 3.95, and you are right to the extent of using the same absolute positioning. However, looking caefully, SL for 3.95 does exactly the same thing as I already dexcribed - it places the receptors in reverse as far to the screen border as possible, but without interfering UI elements.

For now I think your argument of "not DDR, post ITG, same as SL3.95" is not ultimate in the overall context of you directly closing the isse without further discussion. The "same absolute values as in X" and  your arguments do not convice me that it is right as it is setup currently.

Simply Love for sm5 changed so much over time, and got so many things imprved after a tagged "FINAL" release of SL3.95.
Next thing I will do, is to check SLSM5 behavior in a 4:3 setting, to make sure any improvment I may com up with does not crete new problems for 4:3 users. Ultimately I think its 2017, many play on 16:9 hd screens, and we waste valuable distance space on the playfieldfr reverse users.

**Comment by dguzek** [comment]
I am having difficulty following your comments above.  Maybe I'm misunderstanding what you are intending.

Can you share screenshots of what both normal and reverse scroll look like in SM3.95?  If possible, use the default (ITG2) theme as well as Simply Love.  I don't have a means of running SM3.95 and am unsure what you are talking about.  

Additionally, are you suggesting that arrows travel _underneath_ the Gameplay header in Simply Love for SM3.95 both in reverse scroll (always) and in normal scroll (when there is a non-combo)?  It just clicked with me that that is what you might have meant.

**Comment by RodentVienna** [comment]
Hello Dan, 

Let me start by appreciating your uneasiness on "feature ideas and requests" of mine - as this (finally!) lead me to learning git and getting started with programming in a dramatically less half-heartedly way than before.

I created an attempt on a non-destructive solution to the Receptor-Position at Reverse Scroll-Dir here:
https://github.com/RodentVienna/Simply-MORE-Love-SM5/commit/4db8f95470ca5a6b222e456201a1f107fd984a94

This may make it more clear what I was about in regards to the receptor position.

The change makes that StomperZ-exclusive-Player-Option non-exclusive, and accessible to all game modes. I yet want to obtain feedback of other players (i hope to reach those who play reverse in SLSM5), before I will think about creating a PR. One question would be, if the default-setting would be "ITG" or "StomperZ".

Regarding z-index:
In original 3.95 Simply Love, the Arrows indeed do travel above the Gameplay header. While this not much intrusive in Standard Scroll-Dir (most of the arrows are intentionally non-MISSES), you should watch a 10-footer in Reverse Scroll-Dir cluttering the Gameplay header.

I believe this is a separate, yet near issue to the Reverse-Receptor-Pos subject, and I tend to believe this was never really thought of originally by Matt and Lara. 

There may be several possibilities to look at this:
1) keep zindex as it is
2) make arrows completely scroll under gameplay header, no transparencies 
3) make arrows scroll above blac bars, but below UI-elemebts (i.e. below score and lifebar,/songbar)
4) like 3, but there is an additional black-transparent layer between UI-element and arrows (thus darkening the arrows while scrolling under, while keeping UI-elements clean)

The idea is intriguing enough, that I will put it on my to-do list
Lastly I have renamed my fork, and added some text to the ReadMe file.

**Comment by dguzek** [comment]
It is difficult for me to assess the current state of the master branch of your fork of this project as it is currently throwing Lua errors on ScreenGameplay causing the entire UI to break.  You may want to set `ShowThemeErrors=1`and `IgnoredDialogs=` in your Preferences.ini to get a better sense of what is going wrong and how you might fix it.

From what I gather, however, you are trying to give all GameModes (Casual, Competitive, ECFA, StomperZ) the option of positioning the ReceptorArrows to have a `y` value that corresponds to either ITG or StomperZ.  This change alone doesn't really make sense to me, unless you also intend to enforce the smaller header that is used in StomperZ GameMode if either or both players is using StomperZ-positioned Receptor Arrows.  If you intend to pursue this, that would seem to make more sense to me.

> I will think about creating a PR
I would not merge such a pull request into this repository for the reasons discussed in my initial response.

**Comment by dguzek** [comment]
Generally speaking, I do not want to continue working on this project, and I do not want other people working on it, either.  I can't _prevent_ you from continuing to work on your Simply Love fork forever into the future but I would **strongly** prefer that you not. There are (at least) two reasons for this:

* People associate Simply Love for SM5 with me, and I do not want anyone associating features (and misfeatures) I did not author with me.
* I want dance game players to stop using Simply Love.  I want dance game players to use other, new themes.

I'm picky about what pull requests I merge.  Internal code quality, documentation, and front-facing usability matter to me.  At this time, I do not have faith in anyone to pick up work on Simply Love in a way that will represent me in a way I am comfortable with.  More importantly, I do not _want_ anyone to pick up work on Simply Love.  I very much want Simply Love to go away.

Have you considering making a new theme?
