### ISSUE TITLE
Proble im having 

### ISSUE THREAD

**Issue by Maribow** [dguzek/Simply-Love-SM5#90]
i downloaded the theme and i selected it then this message came up "The initial screen set by this theme is not valid.it is not defined anywhere in the theme or in the fallback this is an error in the theme and should be reported to the theme's author"

**Comment by dougshell** [comment]
What version if step mania are you using? This theme is designed to only
work with 5.0.12 and 5.1 b1.

**Comment by Maribow** [comment]
i have no idea how to check

**Comment by dougshell** [comment]
I am at work but Google Stepmania 5.0.12 and install the exe that you find.

Back up your save profile which should be in %appdata. Find your Stepmania
folder, then within that find the Save folder. Copy that folder and keep it
safe. This will contain all your scores.

Launch your new Stepmania 5.0.12 and place Simply Love from this GitHub
into your theme folder.

Let us know what happens once you follow those steps

On Feb 1, 2018 7:33 AM, "Maribow" <notifications@github.com> wrote:

i have no idea how to check

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dguzek/Simply-Love-SM5/issues/90#issuecomment-362252709>,
or mute the thread

**Comment by Maribow** [comment]
thank you ill try it later

**Comment by Maribow** [comment]
it says i already have it

**Comment by dguzek** [comment]
> it says i already have it

Can you clarify what you mean?   Please elaborate on what you've done.

* What did you download?  
* What version of SM5?  
* What version of Simply Love?  
* Where do you have have SM5 installed to?  
* Where do you have Simply Love installed to?
* What told you that you already have it?  What is *it*?

**Comment by Maribow** [comment]
Stepmania 5.0.12
Simply love V4.5 
i have the files saved to my desktop
i have simply love save in the themes folder
i went to install Stepmania 5.0.12 and it said i already had it

**Comment by dguzek** [comment]
Thank you for clarifying.  

It sounds like something is wrong with the copy of the theme you have.  Did you, by chance, delete the other themes in _Themes_ folder that came with StepMania?   If yes, you'll need to uninstall and reinstall a fresh copy of SM5 and keep the themes that came with SM5 as Simply Love needs them to function properly.

If not, maybe try downloading a fresh copy of Simply Love and trying again.  Let us know if you make any progress.

**Comment by dougshell** [comment]
I was thinking this could be the case as the user mentioned fallback issues.

Let us know how it goes

**Comment by Maribow** [comment]
ok will do thx

**Comment by Maribow** [comment]
nothing

**Comment by dguzek** [comment]
> nothing

Can you clarify what you mean?

**Comment by Maribow** [comment]
same thing happend

**Comment by dguzek** [comment]
I mean, can please you clarify what you tried to do to fix the problem?  It is difficult to advise any further without knowing what you've tried and where you're at.

**Comment by Maribow** [comment]
oh i reinstalled both simply love and stepmania 5.0.12

**Comment by dguzek** [comment]
So, you you deleted your old copy of Simply Love and download a new zip from GitHub?

**Comment by Maribow** [comment]
wait ill check i got the right one

**Comment by Maribow** [comment]
i think i got the wrong one and downloading the other

**Comment by Maribow** [comment]
its working now thanks this means a lot to me :)

**Comment by dguzek** [comment]
Glad to hear we got to the bottom of it.
