### ISSUE TITLE
Score Vocalisation?

### ISSUE THREAD

**Issue by lukeoftheaura** [dguzek/Simply-Love-SM5#91]
I've noticed in the extra modifiers menu a score vocalisation option - as this is unavailable in default SM5 I'm assuming it's added by the theme - but aside from "none" there are no options available - would I need to download voice packs? If so, where from?

**Comment by dguzek** [comment]
This is a fair question, as the score vocalization pack isn't mentioned in the included README or anywhere on GitHub.  Please refer this thread on the stepmania.com forums for a link to the vocalization pack and instructions on how to install it:  <https://www.stepmania.com/forums/themes/show/529>

Let me know if this answers the question and, if so, I'll close this issue.

**Comment by dougshell** [comment]
The vocalization pack can be found at the bottom of the first post in the
simply Love thread on Stepmania forum.

https://www.stepmania.com/forums/themes/show/529

**Comment by lukeoftheaura** [comment]
this answered the problem, thanks
