### ISSUE TITLE
Change "mini" to "Note Size"?

### ISSUE THREAD

**Issue by andrewipark** [dguzek/Simply-Love-SM5#97]
As in Rhythm Horizon.

Wanted to get thoughts on this.

**con(s)**:
- People would have to get used to the new numbering scheme.
- I would need to add extra code to the OptionRow to check for the old `Mods.Mini` and convert the value.

**pros**:
- IMO "note size %" is more intuitive and obvious than "Mini%". Increasing Mini% will decrease your note size, but by how much? I had no idea it was 0-200% for 100-0% note size until I opened up this theme's code.
- For features that depend on the size of the receptors (mainly FlashArrowOnMiss), this means that you can pull a value out of `Mods` without having to deal with converting the value in each file.

I have a patch sort of ready for this if this seems like a good idea.

**Comment by dguzek** [comment]
I completely agree that _Note Size_ makes more sense/is more intuitive than ramping up an arbitrary number to make your arrows smaller. My hesitation is entirely that people are just so used to it by now!

**Comment by dguzek** [comment]
I could _maybe_ see an argument being made to use _Note Size_ in StomperZ mode only, but, even then, I'd want to ensure that its scaling system matched whatever is currently being used in Rhythm Horizon...

**Comment by dougshell** [comment]
What about changing from "mini" to "Noteskin Size (Formerly Mini)"

**Comment by dguzek** [comment]
@dougshell  – It's not that I'm concerned about people not adapting to/wanting to adapt to new phrasing; it's that the new system would be inverted and probably use a new scaling factor.

**Comment by RodentVienna** [comment]
The improvment is good enough for forcing people to use the new mod. in my honest opinion. mini is a dreaded curse since it's awakening. Please no more StomperZ exclusiveness :/

**Comment by dguzek** [comment]
@RodentVienna, I disagree.  I personally wouldn't want to have any adjustment period where I was likely to perform worse or fail songs, especially when I'm paying to play.

Furthermore, I'm not interested in changing something that's is firmly established as The ITG Way™.  My reasoning is ultimately the same as it was in issue #87.  Simply Love is an ITG theme for post-ITG players.  It has already overstepped its boundaries in modifying the game that is ITG too much, and I don't want to destabilize an already fragmented community even further by perpetually changing things and saying, "but don't worry, it's still ITG."

_I agree_, making your arrows smaller by scaling a percentage down from 100 makes much more sense than making your arrows smaller by ramping a number up from 0.  ITG does not use Note Size, however; it uses mini.
